### ISSUE TITLE
Failed to close snapshot store

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#17452] opened 2024-04-12 08:17 UTC
**Describe the bug**

During shutdown, the snapshot store cannot be closed in time.
The impact seems to be minimal, mostly just noise during shutdown.

Error group: https://console.cloud.google.com/errors/detail/CLm9r_yto9HpqgE;service=zeebe;time=P7D?project=camunda-saas-int-chaos

**To Reproduce**

Not clear.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
 java.util.concurrent.TimeoutException: Timeout after: 300 SECONDS
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:137) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:208) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.Actor.close(Actor.java:97) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.RaftContext.close(RaftContext.java:815) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.impl.DefaultRaftServer.lambda$shutdown$5(DefaultRaftServer.java:151) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?] 
```

</p>
</details>

**Environment:**
- Zeebe Version: 8.6.0-SNAPSHOT

**Comment by npepinpe** [comment] 2024-04-18 12:07
As impact is minimal, we'll put it in the backlog.

**Comment by deepthidevaki** [comment] 2024-04-24 14:30
This was observed [again](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-04-19T15:35:50.158717729Z;endTime=2024-04-19T16:06:20.234Z;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.project_id%3D%22camunda-saas-int-chaos%22%0Aresource.labels.cluster_name%3D%22worker-chaos-1%22%0Aresource.labels.namespace_name%3D%22ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Atimestamp%3D%222024-04-19T15:35:50.158717729Z%22%0AinsertId%3D%22qax2mfyqwud781o9%22%0Atimestamp%3D%222024-04-19T15:35:50.158717729Z%22%0AinsertId%3D%22qax2mfyqwud781o9%22;startTime=2024-04-19T15:06:20.234Z;summaryFields=jsonPayload%252Fcontext%252FpartitionId:false:32:beginning?project=camunda-saas-int-chaos). It seems the partition is closed after the actor scheduler is closed. 

 ```
 INFO 2024-04-19T15:30:49.745486989Z [jsonPayload.context.partitionId: 1] Transition to INACTIVE on term 13 completed
DEBUG 2024-04-19T15:30:49.745750481Z [jsonPayload.context.partitionId: 1] Shutdown was called with context: PartitionStartupAndTransitionContextImpl{partitionId=1, currentTerm=13, currentRole=INACTIVE}
INFO 2024-04-19T15:30:49.745970379Z [jsonPayload.context.partitionId: 1] Shutdown RocksDB metric timer
DEBUG 2024-04-19T15:30:49.746197436Z [jsonPayload.context.partitionId: 1] Finished shutdown process
INFO 2024-04-19T15:30:49.746437365Z Shutdown Joining Raft Partition
INFO 2024-04-19T15:30:49.823160791Z [jsonPayload.context.partitionId: 1] RaftServer{raft-partition-partition-1} - Transitioning to INACTIVE
DEBUG 2024-04-19T15:30:49.823470286Z transport client closed
INFO 2024-04-19T15:30:49.823803581Z Shutdown Snapshot Store
DEBUG 2024-04-19T15:30:49.823984898Z Gateway broker client closed.
INFO 2024-04-19T15:30:49.824706402Z Shutdown Snapshot Store
INFO 2024-04-19T15:30:49.824985681Z Shutdown Partition Directory
INFO 2024-04-19T15:30:49.825171619Z Shutdown Partition Directory
DEBUG 2024-04-19T15:30:49.825358348Z Finished shutdown process
DEBUG 2024-04-19T15:30:49.825766431Z Finished shutdown process
INFO 2024-04-19T15:30:49.826631936Z Stopped
INFO 2024-04-19T15:30:49.828737688Z Stopped
INFO 2024-04-19T15:30:49.829257817Z 0 - Member deactivated: Member{id=0, address=zeebe-0.zeebe-broker-service.ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAABAAAAAAABAAAAAQAAAAEAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS5lZTQ1YjA0OS0xNTI3LTRhZWYtOGEyOS03YjQ0ZmVhNGM5NWYtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAAMAAAOAAAAOC42LjAtU05BUFNIT1QFAAQBAAAAAAIAAAAAAwAAAAAEAAAAAA==}}
INFO 2024-04-19T15:30:49.829512844Z Stopped
INFO 2024-04-19T15:30:49.830123632Z Local node Member{id=0, address=zeebe-0.zeebe-broker-service.ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAABAAAAAAABAAAAAQAAAAEAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS5lZTQ1YjA0OS0xNTI3LTRhZWYtOGEyOS03YjQ0ZmVhNGM5NWYtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAAMAAAOAAAAOC42LjAtU05BUFNIT1QFAAQBAAAAAAIAAAAAAwAAAAAEAAAAAA==}} left the bootstrap servide
INFO 2024-04-19T15:30:49.830852342Z Stopped cluster membership service for member Member{id=0, address=zeebe-0.zeebe-broker-service.ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe.svc.cluster.local:26502, properties={brokerInfo=EADJAAAABAAAAAAABAAAAAQAAAAEAAAAAAABCgAAAGNvbW1hbmRBcGlfAAAAemVlYmUtMC56ZWViZS1icm9rZXItc2VydmljZS5lZTQ1YjA0OS0xNTI3LTRhZWYtOGEyOS03YjQ0ZmVhNGM5NWYtemVlYmUuc3ZjLmNsdXN0ZXIubG9jYWw6MjY1MDEFAAAMAAAOAAAAOC42LjAtU05BUFNIT1QFAAQBAAAAAAIAAAAAAwAAAAAEAAAAAA==}}
WARNING 2024-04-19T15:30:49.900905379Z Failed to sync with zeebe-gateway-775cc7fc6d-gbbp7
INFO 2024-04-19T15:30:49.934366080Z Stopped plaintext unicast service bound to 0.0.0.0:26502, advertising zeebe-0.zeebe-broker-service.ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe.svc.cluster.local:26502
INFO 2024-04-19T15:30:50.041303047Z Stopped messaging service bound to [0.0.0.0:26502], advertising zeebe-0.zeebe-broker-service.ee45b049-1527-4aef-8a29-7b44fea4c95f-zeebe.svc.cluster.local:26502, and using plaintext
INFO 2024-04-19T15:30:50.042103195Z Stopped
DEBUG 2024-04-19T15:30:50.042829157Z Closing actor thread ground 'zb-fs-workers'
DEBUG 2024-04-19T15:30:50.044031665Z Closing actor thread ground 'zb-actors'
DEBUG 2024-04-19T15:30:50.055590011Z Closing actor thread ground 'zb-fs-workers': closed successfully
DEBUG 2024-04-19T15:30:50.145978444Z [jsonPayload.context.partitionId: 1] Closed database from '/usr/local/zeebe/data/raft-partition/partitions/1/runtime'.
DEBUG 2024-04-19T15:30:50.152349751Z [jsonPayload.context.partitionId: 1] Closing segment: Segment{id=4, index=1848208}
DEBUG 2024-04-19T15:30:50.170806446Z [jsonPayload.context.partitionId: 4] Closed database from '/usr/local/zeebe/data/raft-partition/partitions/4/runtime'.
DEBUG 2024-04-19T15:30:50.174071581Z Closing actor thread ground 'zb-actors': closed successfully
DEBUG 2024-04-19T15:30:50.176340046Z [jsonPayload.context.partitionId: 4] Closing segment: Segment{id=4, index=1756077}
DEBUG 2024-04-19T15:30:50.229188222Z [jsonPayload.context.partitionId: 4] Closing segment: Segment{id=5, index=1828146}
ERROR 2024-04-19T15:35:50.158717729Z [jsonPayload.context.partitionId: 1] RaftServer{raft-partition-partition-1} - Failed to close snapshot store
ERROR 2024-04-19T15:35:50.234097507Z [jsonPayload.context.partitionId: 4] RaftServer{raft-partition-partition-4} - Failed to close snapshot store
```

Here partiiton 1 and 4 is being closed after actor scheduler is closed.

**Comment by deepthidevaki** [comment] 2024-06-25 09:18
I couldn't reproduce this. 

There is nothing in the code that indicate the above hypothesis that partitions are closed after the actor scheduler is closed. Also I couldn't reproduce this case.

One potential cause is that `SnapshotStore` is closed twice - First by `RaftContext`, then by the Partition via its startup steps. A hypothesis is that the second close failed because of some race condition. Usually, closing an already closed actor should succeed. However, in this case probably there was a race-condition. I don't have any explanation for a potential race condition. Initially, I thought it could be due to the shared close future. But looking at the code, it should be thread safe. 

For now, I will remove the duplicate close in `RaftContext` and assume this issue is fixed. This issue hasn't occurred in a long time.

**Closed** 2024-06-25 11:40 UTC
Labels: kind/bug, good first issue, severity/low, impact/low, likelihood/mid, component/zeebe
