### ISSUE TITLE
Flaky test `PartitionJoinTest.canLeavePartitionAfterJoining `

### ISSUE THREAD

**Issue by mustafadagher** [camunda/camunda#19354] opened 2024-06-13 14:20 UTC
**Summary**

- How often does the test fail? [once](https://github.com/camunda/camunda/actions/runs/9501026145)
- Does it block your work? it blocks merging the PR for now.
- Do we suspect that it is a real failure? no

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
canLeavePartitionAfterJoining(Scenario)[2] scenario=Scenario[initialClusterState=InitialClusterState[clusterSize=2, partitionCount=2, replicationFactor=1], operation=Operation[brokerId=1, partitionId=1, priority=2]] (Flaky Test): io.camunda.zeebe.it.clustering.dynamic.PartitionJoinTest
org.awaitility.core.ConditionTimeoutException: 
Condition with alias 'until cluster topology is complete' didn't complete within 2 minutes because assertion condition defined as a Lambda expression in io.camunda.zeebe.qa.util.cluster.TestCluster 
Expecting all elements of:
  [TestStandaloneBroker{nodeId = 1},
    TestStandaloneBroker{nodeId = 0},
    TestStandaloneGateway{nodeId = gateway-0}]
to satisfy given requirements, but these elements did not:

TestStandaloneGateway{nodeId = gateway-0}
error: Expected all partitions to be healthy, but partition <1> of broker <1> is <UNHEALTHY>.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:1006)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:790)
	at io.camunda.zeebe.qa.util.cluster.TestCluster.awaitHealthyTopology(TestCluster.java:333)
	at io.camunda.zeebe.qa.util.cluster.TestCluster.awaitHealthyTopology(TestCluster.java:326)
	at io.camunda.zeebe.it.clustering.dynamic.PartitionJoinTest.canLeavePartitionAfterJoining(PartitionJoinTest.java:59)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.AssertionError: 
Expecting all elements of:
  [TestStandaloneBroker{nodeId = 1},
    TestStandaloneBroker{nodeId = 0},
    TestStandaloneGateway{nodeId = gateway-0}]
to satisfy given requirements, but these elements did not:

TestStandaloneGateway{nodeId = gateway-0}
error: Expected all partitions to be healthy, but partition <1> of broker <1> is <UNHEALTHY>
	at io.camunda.zeebe.qa.util.cluster.TestCluster.lambda$awaitHealthyTopology$8(TestCluster.java:333)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:248)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:235)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

</pre>
</details>

**Hypotheses**

**Logs**

[Test results for [IT] QA Integration Tests.zip](https://github.com/user-attachments/files/15821921/Test.results.for.IT.QA.Integration.Tests.zip)

**Comment by deepthidevaki** [comment] 2024-06-26 13:47
Couldn't reproduce it. 

Checking the logs, we see that the last METADATA_CHANGED event recieved by the gateway is after Partition 1 is added to Broker 1. It did not receive an updated after partition 1 has left broker 1. 

```
14:06:54.437 [] [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.swim.sync - gateway-0 - Start synchronizing membership with Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQABAgAAAAAMAAECAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604463}
14:06:54.438 [] [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.swim.sync - gateway-0 - Finished synchronizing membership with Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQABAgAAAAAMAAECAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604463}, received: '[Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQABAgAAAAAMAAECAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAECAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604463}, Member{id=gateway-0, address=0.0.0.0:1258, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604437, state=ALIVE, incarnationNumber=1718287604437}, Member{id=0, address=0.0.0.0:1244, properties={brokerInfo=EADJAAAABQAAAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjQzBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604425, state=ALIVE, incarnationNumber=1718287604426}]'

Broker 1 Join Partition 1
14:06:54.669 [Broker-0] [] [zb-actors-0] DEBUG io.camunda.zeebe.dynamic.config.changes.ConfigurationChangeCoordinatorImpl - Applying the topology change has started.

14:06:54.716 [] [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.swim - gateway-0 - Member metadata changed Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQACAQAAAAECAAAAAAwAAQIAAAABAAAAAAAAAA4AAAA4LjYuMC1TTkFQU0hPVAUAAgEAAAAAAgAAAAE=, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}}
14:06:54.717 [] [] [atomix-cluster-events] DEBUG io.camunda.zeebe.broker.client.impl.BrokerTopologyManagerImpl - Received metadata change from Broker 1, partitions {1=FOLLOWER, 2=LEADER}, terms {2=1} and health {1=UNHEALTHY, 2=HEALTHY}.

Broker 1 LEAVE Partition 1
14:06:54.800 [Broker-0] [] [zb-actors-0] DEBUG io.camunda.zeebe.dynamic.config.changes.ConfigurationChangeCoordinatorImpl - Applying the topology change has started.
14:06:54.817 [Broker-1] [Startup] [zb-actors-1] INFO  io.camunda.zeebe.broker.partitioning.PartitionManagerImpl - Left partition 1
```
After this point, not topology update. We see that gateway is syncing with Broker 1 successfully. 

```
14:07:14.439 [] [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.swim.sync - gateway-0 - Start synchronizing membership with Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQACAQAAAAECAAAAAAwAAQIAAAABAAAAAAAAAA4AAAA4LjYuMC1TTkFQU0hPVAUAAgEAAAAAAgAAAAE=, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604464}
14:07:14.440 [] [] [atomix-cluster-heartbeat-sender] DEBUG io.atomix.cluster.protocol.swim.sync - gateway-0 - Finished synchronizing membership with Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQACAQAAAAECAAAAAAwAAQIAAAABAAAAAAAAAA4AAAA4LjYuMC1TTkFQU0hPVAUAAgEAAAAAAgAAAAE=, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604464}, received: '[Member{id=1, address=0.0.0.0:1251, properties={brokerInfo=EADJAAAABQABAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjUwBQABAgAAAAAMAAECAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAIBAAAAAAIAAAAB, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604462, state=ALIVE, incarnationNumber=1718287604464}, Member{id=gateway-0, address=0.0.0.0:1258, properties={event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604437, state=ALIVE, incarnationNumber=1718287604437}, Member{id=0, address=0.0.0.0:1244, properties={brokerInfo=EADJAAAABQAAAAAAAgAAAAIAAAABAAAAAAABCgAAAGNvbW1hbmRBcGkMAAAAMC4wLjAuMDoxMjQzBQABAQAAAAAMAAEBAAAAAQAAAAAAAAAOAAAAOC42LjAtU05BUFNIT1QFAAEBAAAAAQ==, event-service-topics-subscribed=KIIDAGpvYnNBdmFpbGFibOU=}, version=8.6.0-SNAPSHOT, timestamp=1718287604425, state=ALIVE, incarnationNumber=1718287604426}]'
```
So, somehow the topology update is lost. It is not clear, if it is lost in SWIM or if the `TopologyManager` did not update it correctly.

What is strange is that we see several errors on transport
```
14:06:56.864 [] [] [netty-messaging-event-epoll-client-6] WARN  io.atomix.cluster.messaging.impl.NettyMessagingService - Received invalid handshake, closing connection
14:06:56.864 [] [] [grpc-default-worker-ELG-5-14] INFO  io.grpc.netty.NettyServerTransport.connections - Transport failed
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: cb65f7b10002
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:107) ~[netty-codec-http2-4.1.110.Final.jar:4.1.110.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:319) ~[netty-codec-http2-4.1.110.Final.jar:4.1.110.Final]
```
But it doesn't seem to affect periodic sync. So it is unlikely that gateway did not receive via swim.

**Comment by deepthidevaki** [comment] 2024-08-15 08:48
I don't think we can get any more useful data to investigate this. The transport error `HTTP/2 client preface string missing or corrupt. ` makes me think that it could be something weird in the infra. As it has not happened again, I think we can close this issue. Let's revisit if it occurs again.

**Closed** 2024-08-15 08:48 UTC
Labels: kind/flake, component/zeebe
