### ISSUE TITLE
Config go-apidiff CI task with the correct reference branch/tag instead of the hardcoded ones

### ISSUE THREAD

**Issue by abbasadel** [camunda/camunda#12838] opened 2023-05-23 12:56 UTC
**Describe the bug**
`go-apidiff` is used to check the go-client backward compatibility against to the PR target branch. Since we use `bors` as a merge tool, it does not work with `go-apidiff` since `bors` does not set `$GITHUB_BASE_REF` which is needed for `go-apidiff` to work correctly.

**To Reproduce**
1. Edit ci.yml, `go-apidiff` task
```
- uses: joelanford/go-apidiff@main
  with:
    # bors-ng fails to set ${GITHUB_BASE_REF} to the target PR branch which breaks go-apidiff
    base-ref: origin/stable/8.0
```
2. Remove `base-ref` which will make `go-apidiff` defaults to `$GITHUB_BASE_REF`
3. Create PR against `stable/8.*`, the github PR checks should work normally
4. run `bors try` and it will fail, producing the following error:
```
/home/runner/go/bin/go-apidiff origin/ --compare-imports=false --print-compatible=true --repo-path=.
failed to lookup git commit hashes: could not get hash for "origin/": Revision invalid : must not end with "/"
```

**Expected behavior**
- make `go-apidiff` task work with `bors merge` 
- handle merging to different branches (main, stable/* , and release/*  branches)

**Log/Stacktrace**
[bors.log](https://github.com/camunda/zeebe/files/11544083/bors.log)

**Caused by:** https://github.com/camunda/zeebe/issues/12838
**Relates to:** https://github.com/bors-ng/bors-ng/issues/1659

**Comment by korthout** [comment] 2023-05-24 08:45
ZPA triage:
- not a bug, but it affects our CI pipeline
- we want to automate this so we don't have to do manual work
- @abbasadel please also add this manual work as a step in the release process
- we don't yet know how to resolve this problem automatically

**Comment by megglos** [comment] 2024-09-20 21:10
closing as not planned due to https://github.com/camunda/camunda/issues/21817

**Closed by megglos** 2024-09-20 21:10 UTC
Labels: kind/toil, scope/clients-go, area/build, go, component/zeebe
