### ISSUE TITLE
Partitions in Zeebe are stuck at 100% backpressure forever during backup + load

### ISSUE THREAD

**Issue by ashprojects** [camunda/camunda#20126] opened 2024-07-07 18:05 UTC
**Describe the bug**

Some Zeebe Partition gets stuck at 100% backpressure forever, even though load is minimal
I have attached logs during the timeframe.

We have noticed that some partitions would permanently start firing backpressure 100% even though load is limited.
<img width="832" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/f710e16d-ce28-4275-80df-cf3fa1ce6c2f">

We see all partitions as healthy but backpressure % is 100 for some of the partitions
<img width="856" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/fbd44794-f317-4388-a75e-c15c2780b363">

On some metric observations I see this
<img width="1116" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/0f08e22f-750e-4e60-aa34-8271dfd24964">

Job activated per second is also 0
<img width="550" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/312acfe6-fedb-47c2-a5ba-7d6ebc0af0fc">

PVC / CPU / Memory is normal
<img width="834" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/68dc38c7-6342-4469-8547-769112bf9986">
<img width="1687" alt="image" src="https://github.com/camunda/camunda-bpm-platform/assets/15957226/daeb1a82-77da-4dd0-aad0-baa82ec796f5">

**To Reproduce**
Looks like this happened when we are trying to take backup of Zeebe via Backup REST API.
As per logs, I see electionTimeout and backup is stuck, and backpressure stuck too.
Is there a possibility that backup + leader re-election makes backpressure go 100% for failed partitions?

**Expected behavior**
Backpressure should get released and system should be back in stable state

**Log/Stacktrace**
Some stack traces from one of the brokers; which show connection timeout, even though there is no network issue
```
 2024-07-06 12:40:52.846 [Broker-0] [raft-server-0-7] [raft-server-7] INFO                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - No heartbeat from a known leader since 1987854ms                                                                                             │                                        │
│ 2024-07-06 12:40:52.846 [Broker-0] [raft-server-0-7] [raft-server-7] INFO                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Sending poll requests to all active members: [DefaultRaftMember{id=6, type=ACTIVE, updated=2024-07-05T07:26:31.484Z}, DefaultRaftMember{id=7 │                                        │
│ 2024-07-06 12:40:55.347 [Broker-0] [raft-server-0-7] [raft-server-7] WARN                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Poll request to 6 failed: java.util.concurrent.TimeoutException: Request raft-partition-partition-7-poll to camunda-zeebe-6.camunda-zeebe.ca │                                        │
│ 2024-07-06 12:40:55.347 [Broker-0] [raft-server-0-7] [raft-server-7] WARN                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Poll request to 7 failed: java.util.concurrent.TimeoutException: Request raft-partition-partition-7-poll to camunda-zeebe-7.camunda-zeebe.ca │                                        │
│ 2024-07-06 12:41:02.847 [Broker-0] [raft-server-0-7] [raft-server-7] INFO                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - No heartbeat from a known leader since 1997855ms                                                                                             │                                        │
│ 2024-07-06 12:41:02.848 [Broker-0] [raft-server-0-7] [raft-server-7] INFO                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Sending poll requests to all active members: [DefaultRaftMember{id=6, type=ACTIVE, updated=2024-07-05T07:26:31.484Z}, DefaultRaftMember{id=7 │                                        │
│ 2024-07-06 12:41:05.348 [Broker-0] [raft-server-0-7] [raft-server-7] WARN                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Poll request to 6 failed: java.util.concurrent.TimeoutException: Request raft-partition-partition-7-poll to camunda-zeebe-6.camunda-zeebe.ca │                                        │
│ 2024-07-06 12:41:05.349 [Broker-0] [raft-server-0-7] [raft-server-7] WARN                                                                                                                                                                      │                                        │
│       io.atomix.raft.roles.FollowerRole - RaftServer{raft-partition-partition-7}{role=FOLLOWER} - Poll request to 7 failed: java.util.concurrent.TimeoutException: Request raft-partition-partition-7-poll to camunda-zeebe-7.camunda-zeebe.ca │                                        │
│ 2024-07-06 12:41:06.344 [Broker-0] [zb-actors-2] [InterPartitionCommandReceiverActor-8] WARN                                                                                                                                                   │                                        │

```
**Environment:**
- OS: Linux
- Zeebe Version: 8.5.2
- Configuration: 
Elastic Search Exporter Configured
Partitions: 16
Brokers: 8
CPU: 4
Memory: 16GB
PVC: 32GB
Deployed in EKS via Helm

[logs-insights-results (4).csv](https://github.com/user-attachments/files/16120225/logs-insights-results.4.csv)

**Comment by ashprojects** [comment] 2024-07-07 18:08
I had to manually kill pods by analysing the topology. I stopped backup by calling DELETE API and error hasn't appeared since then.
This looks like a bug.

**Comment by ashprojects** [comment] 2024-07-09 15:15
We stopped backup job and haven't experience this issue since then

**Comment by deepthidevaki** [comment] 2024-07-10 10:21
I assume this is a duplicate of https://github.com/camunda/camunda/issues/20177

**Comment by npepinpe** [comment] 2024-08-26 12:57
I will close it in favor of #20177

**Closed by npepinpe** 2024-08-26 12:57 UTC
Labels: kind/bug, component/zeebe
