### ISSUE TITLE
Instance migration subscribes element instance with incident to message event 

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#19212] opened 2024-06-10 09:52 UTC
We detected an inconsistency while processing the following record:
```
Expected to process record 'LoggedEvent [position=3534407, key=4503599629136776, timestamp=1717796404395, sourceEventPosition=-1] RecordMetadata{recordType=COMMAND, valueType=INCIDENT, intent=RESOLVE, authorization=[REDACTED]}' successfully on stream processor, but caught unrecoverable exception.
```

Full stacktrace:

```
 io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{4503599629136774}, second=DbTenantAwareKey[tenantKey=<default>, wrappedKey=[REDACTED], placementType=PREFIX]} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.assertKeyDoesNotExist(TransactionalColumnFamily.java:316) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$insert$0(TransactionalColumnFamily.java:87) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.lambda$ensureInOpenTransaction$19(TransactionalColumnFamily.java:344) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.DefaultTransactionContext.runInTransaction(DefaultTransactionContext.java:31) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.ensureInOpenTransaction(TransactionalColumnFamily.java:343) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.TransactionalColumnFamily.insert(TransactionalColumnFamily.java:82) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.message.DbProcessMessageSubscriptionState.put(DbProcessMessageSubscriptionState.java:94) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:28) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.ProcessMessageSubscriptionCreatingApplier.applyState(ProcessMessageSubscriptionCreatingApplier.java:15) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:440) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:56) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.streamprocessor.writers.ResultBuilderBackedEventApplyingStateWriter.appendFollowUpEvent(ResultBuilderBackedEventApplyingStateWriter.java:42) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvent(CatchEventBehavior.java:299) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToMessageEvents$10(CatchEventBehavior.java:273) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToMessageEvents(CatchEventBehavior.java:273) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.lambda$subscribeToEvents$7(CatchEventBehavior.java:181) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRight(Either.java:428) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:179) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.common.CatchEventBehavior.subscribeToEvents(CatchEventBehavior.java:151) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.behavior.BpmnEventSubscriptionBehavior.subscribeToEvents(BpmnEventSubscriptionBehavior.java:48) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.lambda$finalizeActivation$1(JobWorkerTaskProcessor.java:65) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskProcessor.finalizeActivation(JobWorkerTaskProcessor.java:65) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.finalizeActivation(JobWorkerTaskSupportingProcessor.java:39) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.task.JobWorkerTaskSupportingProcessor.finalizeActivation(JobWorkerTaskSupportingProcessor.java:18) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processElementWithListeners(BpmnStreamProcessor.java:236) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.afterActivating(BpmnStreamProcessor.java:204) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processEvent$3(BpmnStreamProcessor.java:162) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.flatMap(Either.java:417) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processEvent(BpmnStreamProcessor.java:162) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.lambda$processRecord$0(BpmnStreamProcessor.java:110) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.bpmn.BpmnStreamProcessor.processRecord(BpmnStreamProcessor.java:107) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.lambda$attemptToContinueProcessProcessing$0(IncidentResolveProcessor.java:113) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.util.Either$Right.ifRightOrLeft(Either.java:438) ~[zeebe-util-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.attemptToContinueProcessProcessing(IncidentResolveProcessor.java:111) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.processing.incident.IncidentResolveProcessor.processRecord(IncidentResolveProcessor.java:90) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:369) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:282) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:240) ~[zeebe-stream-platform-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.1.jar:8.5.1]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.1.jar:8.5.1] 
```

Error Group: https://console.cloud.google.com/errors/detail/CPDM9-CV9Nvk3wE;service=zeebe;time=P7D?project=camunda-saas-prod
Incident: https://camunda.slack.com/archives/C0778L3662G
Data from zeebe-2: https://drive.google.com/file/d/1JV1K0GwibNRBHMrAI8l5670GLyZYc38h/view?usp=drive_link

**Comment by lenaschoenburg** [comment] 2024-06-10 10:36
Marked as critical because it's a new data inconsistency that we need to investigate. Until this is resolved, affected partitions are stuck and we have at least partial unavailability.

**Comment by korthout** [comment] 2024-06-10 15:42
@nicpuppa and I looked into this bug, and were able to figure out the root cause.

An incident is being resolved, and as a result attempts to continue the processing of a User Task activation. Part of this is subscribing to its events, in this case a message boundary event. Subscribing fails because a message subscription already exists for this element instance and message name.

We discovered that the problem already exists in the snapshot:
- The User Task is activating because it has an incident
- But there is already a (process) message subscription for it

```
zdb state list -p raft-partition/partitions/2/snapshots/3531646-9-3534405-3533962  | grep 4503599629136774
{"cf":"ELEMENT_INSTANCE_KEY","key":"00 00 00 00 00 00 00 07 00 10 00 00 00 1a f3 86","value":{"parentKey":4503599628808684,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":4503599629136774,"state":"ELEMENT_ACTIVATING","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"<redacted>","bpmnProcessId":"<redacted>","version":30,"processDefinitionKey":2251799815447677,"processInstanceKey":4503599628808684,"flowScopeKey":4503599628808684,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0,"userTaskKey":-1,"executionListenerIndex":0}},
{"cf":"MESSAGE_SUBSCRIPTION_BY_KEY","key":"4503599629136774:Message_btsCmrRollback","value":{"record":{"processInstanceKey":4503599628808684,"elementInstanceKey":4503599629136774,"messageKey":-1,"messageName":"<redacted>","correlationKey":"<redacted>","interrupting":true,"bpmnProcessId":"<redacted>","variables":"<redacted>","tenantId":"<redacted>"},"key":4503599629136871,"correlating":false}},
{"cf":"INCIDENTS","key":"00 00 00 00 00 00 00 22 00 10 00 00 00 1a f3 88","value":{"incidentRecord":{"errorType":"EXTRACT_VALUE_ERROR","errorMessage":"Expected result of the expression '<redacted>' to be 'ARRAY', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name '<redacted>'","bpmnProcessId":"<redacted>","processDefinitionKey":2251799815447677,"processInstanceKey":4503599628808684,"elementId":"<redacted>","elementInstanceKey":4503599629136774,"jobKey":-1,"variableScopeKey":4503599629136774,"tenantId":"<redacted>"}}},
{"cf":"PROCESS_SUBSCRIPTION_BY_KEY","key":"00 00 00 00 00 00 00 4b 00 10 00 00 00 1a f3 86 00 00 00 09 3c 64 65 66 61 75 6c 74 3e 00 00 00 16 4d 65 73 73 61 67 65 5f 62 74 73 43 6d 72 52 6f 6c 6c 62 61 63 6b","value":{"record":{"subscriptionPartitionId":2,"processInstanceKey":4503599628808684,"elementInstanceKey":4503599629136774,"messageKey":-1,"messageName":"<redacted>","variables":"<redacted>","interrupting":true,"bpmnProcessId":"<redacted>","correlationKey":"<redacted>","elementId":"<redacted>","tenantId":"<redacted>"},"state":"STATE_OPENED","key":4503599629136870}}]}
```

Looking at the log, we discovered that this process instance was migrated previously:
```
zdb log print --instanceKey 4503599628808684 -p ./raft-partition/partitions/2/
...
      {
        "position": 3534265,
        "sourceRecordPosition": 3534231,
        "timestamp": 1717796374295,
        "key": 4503599628808684,
        "recordType": "EVENT",
        "valueType": "PROCESS_INSTANCE_MIGRATION",
        "intent": "MIGRATED",
        "requestId": -1,
        "requestStreamId": -2147483648,
        "protocolVersion": 4,
        "brokerVersion": "8.5.1",
        "recordVersion": 1,
        "recordValue": {
          "processInstanceKey": 4503599628808684,
          "targetProcessDefinitionKey": 2251799815447677,
          "mappingInstructions": [
            {
              "sourceElementId": "<redacted_user_task>",
              "targetElementId": "<redacted_user_task>"
            }
          ]
        }
      },
```

The migration attempt had migrated the process instance, the user task's element instance, the incident, and it had created new (process) message subscription. Note that the source record position is the same as in the `MIGRATED` event.

```
      {
        "position": 3534263,
        "sourceRecordPosition": 3534231,
        "timestamp": 1717796374295,
        "key": 4503599629136870,
        "recordType": "EVENT",
        "valueType": "PROCESS_MESSAGE_SUBSCRIPTION",
        "intent": "CREATING",
        "requestId": -1,
        "requestStreamId": -2147483648,
        "protocolVersion": 4,
        "brokerVersion": "8.5.1",
        "recordVersion": 1,
        "recordValue": {
          "subscriptionPartitionId": 2,
          "processInstanceKey": 4503599628808684,
          "elementInstanceKey": 4503599629136774,
          "messageKey": -1,
          "messageName": "<redacted>",
          "variables": "<redacted>",
          "interrupting": true,
          "bpmnProcessId": "<redacted>",
          "correlationKey": "<redacted>",
          "elementId": "<redacted>",
          "tenantId": "<redacted>"
        }
      }
```

A reproducing test case can be found here: https://github.com/camunda/camunda/compare/stable/8.5...korthout-nicpuppa-19212-corruption-due-to-migration

**Comment by korthout** [comment] 2024-06-10 15:43
@nicpuppa and I looked into this bug, and were able to figure out the root cause.

An incident is being resolved, and as a result attempts to continue the processing of a User Task activation. Part of this is subscribing to its events, in this case a message boundary event. Subscribing fails because a message subscription already exists for this element instance and message name.

We discovered that the problem already exists in the snapshot:
- The User Task is activating because it has an incident
- But there is already a (process) message subscription for it

```
zdb state list -p raft-partition/partitions/2/snapshots/3531646-9-3534405-3533962  | grep 4503599629136774
{"cf":"ELEMENT_INSTANCE_KEY","key":"00 00 00 00 00 00 00 07 00 10 00 00 00 1a f3 86","value":{"parentKey":4503599628808684,"childCount":0,"childActivatedCount":0,"childCompletedCount":0,"childTerminatedCount":0,"jobKey":0,"multiInstanceLoopCounter":0,"interruptingElementId":"","calledChildInstanceKey":-1,"elementRecord":{"key":4503599629136774,"state":"ELEMENT_ACTIVATING","processInstanceRecord":{"bpmnElementType":"USER_TASK","elementId":"<redacted>","bpmnProcessId":"<redacted>","version":30,"processDefinitionKey":2251799815447677,"processInstanceKey":4503599628808684,"flowScopeKey":4503599628808684,"bpmnEventType":"UNSPECIFIED","parentProcessInstanceKey":-1,"parentElementInstanceKey":-1,"tenantId":"<default>"}},"activeSequenceFlows":0,"userTaskKey":-1,"executionListenerIndex":0}},
{"cf":"MESSAGE_SUBSCRIPTION_BY_KEY","key":"4503599629136774:<redacted>","value":{"record":{"processInstanceKey":4503599628808684,"elementInstanceKey":4503599629136774,"messageKey":-1,"messageName":"<redacted>","correlationKey":"<redacted>","interrupting":true,"bpmnProcessId":"<redacted>","variables":"<redacted>","tenantId":"<redacted>"},"key":4503599629136871,"correlating":false}},
{"cf":"INCIDENTS","key":"00 00 00 00 00 00 00 22 00 10 00 00 00 1a f3 88","value":{"incidentRecord":{"errorType":"EXTRACT_VALUE_ERROR","errorMessage":"Expected result of the expression '<redacted>' to be 'ARRAY', but was 'NULL'. The evaluation reported the following warnings:\n[NO_VARIABLE_FOUND] No variable found with name '<redacted>'","bpmnProcessId":"<redacted>","processDefinitionKey":2251799815447677,"processInstanceKey":4503599628808684,"elementId":"<redacted>","elementInstanceKey":4503599629136774,"jobKey":-1,"variableScopeKey":4503599629136774,"tenantId":"<redacted>"}}},
{"cf":"PROCESS_SUBSCRIPTION_BY_KEY","key":"00 00 00 00 00 00 00 4b 00 10 00 00 00 1a f3 86 00 00 00 09 3c 64 65 66 61 75 6c 74 3e 00 00 00 16 4d 65 73 73 61 67 65 5f 62 74 73 43 6d 72 52 6f 6c 6c 62 61 63 6b","value":{"record":{"subscriptionPartitionId":2,"processInstanceKey":4503599628808684,"elementInstanceKey":4503599629136774,"messageKey":-1,"messageName":"<redacted>","variables":"<redacted>","interrupting":true,"bpmnProcessId":"<redacted>","correlationKey":"<redacted>","elementId":"<redacted>","tenantId":"<redacted>"},"state":"STATE_OPENED","key":4503599629136870}}]}
```

Looking at the log, we discovered that this process instance was migrated previously:
```
zdb log print --instanceKey 4503599628808684 -p ./raft-partition/partitions/2/
...
      {
        "position": 3534265,
        "sourceRecordPosition": 3534231,
        "timestamp": 1717796374295,
        "key": 4503599628808684,
        "recordType": "EVENT",
        "valueType": "PROCESS_INSTANCE_MIGRATION",
        "intent": "MIGRATED",
        "requestId": -1,
        "requestStreamId": -2147483648,
        "protocolVersion": 4,
        "brokerVersion": "8.5.1",
        "recordVersion": 1,
        "recordValue": {
          "processInstanceKey": 4503599628808684,
          "targetProcessDefinitionKey": 2251799815447677,
          "mappingInstructions": [
            {
              "sourceElementId": "<redacted_user_task>",
              "targetElementId": "<redacted_user_task>"
            }
          ]
        }
      },
```

The migration attempt had migrated the process instance, the user task's element instance, the incident, and it had created new (process) message subscription. Note that the source record position is the same as in the `MIGRATED` event.

```
      {
        "position": 3534263,
        "sourceRecordPosition": 3534231,
        "timestamp": 1717796374295,
        "key": 4503599629136870,
        "recordType": "EVENT",
        "valueType": "PROCESS_MESSAGE_SUBSCRIPTION",
        "intent": "CREATING",
        "requestId": -1,
        "requestStreamId": -2147483648,
        "protocolVersion": 4,
        "brokerVersion": "8.5.1",
        "recordVersion": 1,
        "recordValue": {
          "subscriptionPartitionId": 2,
          "processInstanceKey": 4503599628808684,
          "elementInstanceKey": 4503599629136774,
          "messageKey": -1,
          "messageName": "<redacted>",
          "variables": "<redacted>",
          "interrupting": true,
          "bpmnProcessId": "<redacted>",
          "correlationKey": "<redacted>",
          "elementId": "<redacted>",
          "tenantId": "<redacted>"
        }
      }
```

A reproducing test case can be found here: https://github.com/camunda/camunda/compare/stable/8.5...korthout-nicpuppa-19212-corruption-due-to-migration

**Comment by korthout** [comment] 2024-06-11 11:19
# How to know that you ran into this same bug?

You've ran into this bug if the following is true:
- Your partition is marked as `DEAD`
  - A `ZeebeDbInconsistentException` error was logged `io.camunda.zeebe.db.ZeebeDbInconsistentException: Key DbCompositeKey{first=DbLong{4503599629136774}, second=DbTenantAwareKey[tenantKey=<default>, wrappedKey=[REDACTED], placementType=PREFIX]} in ColumnFamily PROCESS_SUBSCRIPTION_BY_KEY already exists`
- You used [Process Instance Migration](https://docs.camunda.io/docs/next/components/concepts/process-instance-migration/) on a process instance that already has an [Incident](https://docs.camunda.io/docs/next/components/concepts/incidents/). 
- This incident was created during the activation of the activity (e.g. a [Task](https://docs.camunda.io/docs/next/components/modeler/bpmn/tasks/), [Sub Process](https://docs.camunda.io/docs/next/components/modeler/bpmn/embedded-subprocesses/), etc), for example because an [Expression](https://docs.camunda.io/docs/next/components/concepts/expressions/) could not be evaluated successfully. 
- A [Message Boundary Event](https://docs.camunda.io/docs/next/components/modeler/bpmn/message-events/#message-boundary-events) is attached to the activity with the incident.
- You've tried to resolve the Incident, this caused the exception.

# How to recover from the bug?

If the above is true, you've encountered this bug and there is a way to safely recover:
- Disable [`ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS`](https://github.com/camunda/camunda/blob/72bcf0e4bcc10cbd55353833d96fbdcd05dd9698/dist/src/main/config/broker.yaml.template#L1004-L1008): You can do this safely in this case, as long as you follow the rest of these steps as well
- Restart the brokers
- Use Process Instance Modification to terminate and (re)activate the activity with incident
- Re-enable `ZEEBE_BROKER_EXPERIMENTAL_CONSISTENCYCHECKS_ENABLEPRECONDITIONS`

**Closed** 2024-06-14 10:34 UTC
Labels: kind/bug, severity/critical, incident, likelihood/low, component/zeebe, version:8.5.3
