### ISSUE TITLE
Failure to resolve DNS entry

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#7019] opened 2021-05-10 11:23 UTC
**Describe the bug**
Observed in benchmark log: https://console.cloud.google.com/errors/CPHr1prk786i-AE?service=zeebe-gateway&version=medic-cw-15-ca1979db1-benchmark&time=P7D&project=zeebe-io

**Log/Stacktrace**
<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Failed to bootstrap client (address medic-cw-15-ca1979db1-benchmark-zeebe-0.medic-cw-15-ca1979db1-benchmark-zeebe.medic-cw-15-ca1979db1-benchmark.svc.cluster.local:26501 cannot be resolved)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.bootstrapClient(NettyMessagingService.java:540) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.openChannel(NettyMessagingService.java:524) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.ChannelPool.getChannel(ChannelPool.java:96) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:415) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:378) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:195) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:174) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.atomix.cluster.messaging.MessagingService.sendAndReceive(MessagingService.java:135) ~[atomix-cluster-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:148) ~[zeebe-transport-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2(AtomixClientTransportAdapter.java:86) ~[zeebe-transport-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorControl.lambda$call$0(ActorControl.java:136) ~[zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.invoke(ActorJob.java:62) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at io.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
```

</p>
</details>

**Environment:**
 - OS: Linux
 - Zeebe Version/Configuration:  zeebe-gateway:medic-cw-15-ca1979db1-benchmark

**Comment by pihme** [comment] 2021-05-10 11:25
No discernible impact. Benchmark is running normally.

**Comment by npepinpe** [comment] 2021-05-11 13:12
Let's ask someone from infra if they have any ideas - I'm not too worried about it however, since it seems like it was transient, and the address seems correct. Maybe it's something possible in GKE that DNS entries are lagging behind a little after scheduling?

**Comment by korthout** [comment] 2021-06-07 12:09
This error appeared again in benchmark error reporting: https://console.cloud.google.com/errors/CPHr1prk786i-AE?service=zeebe-gateway&time=P7D&project=zeebe-io&authuser=1&organizationId=669107107215 (benchmark calendar week 19).

While searching for related issues I ran into the older #5519, which appears to be a duplicate of this issue but occurs in Camunda Cloud instead of in the benchmarks. 

ping @npepinpe just to keep you aware of this issue

**Comment by npepinpe** [comment] 2021-06-07 13:52
It seems the benchmark was already deleted? These errors also seem to all have occurred around when you commented. Did they occur during the deletion of the cluster possibly?

**Comment by korthout** [comment] 2021-06-07 14:06
Interesting, I did not notice that. But yes, there's about 3 minutes between deleting the benchmark and these logs. I did not actually stop the benchmark before deleting it. Perhaps that is related to this.

**Comment by npepinpe** [comment] 2021-06-15 09:47
Let's keep an eye on it and see if it's related. It's always possible that things are deleted asynchronously and suddenly some node is simply not available anymore.

**Comment by npepinpe** [comment] 2021-07-14 12:17
At any rate, this is something that can happen in Kubernetes. It's possible that a node starts before all DNS entries are created, for example. This shouldn't be logged as an error but as a warning, as it may be temporary only.

**Comment by Zelldon** [comment] 2022-12-29 06:19
```
java.lang.IllegalStateException: Failed to bootstrap client (address medic-cw-52-cce4510-benchmark-zeebe-1.medic-cw-52-cce4510-benchmark-zeebe.medic-cw-52-cce4510-benchmark.svc:26501 cannot be resolved)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.bootstrapClient(NettyMessagingService.java:692) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.openChannel(NettyMessagingService.java:676) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.ChannelPool.getChannel(ChannelPool.java:96) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:545) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.executeOnPooledConnection(NettyMessagingService.java:509) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:239) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.impl.NettyMessagingService.sendAndReceive(NettyMessagingService.java:216) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.atomix.cluster.messaging.MessagingService.sendAndReceive(MessagingService.java:135) ~[zeebe-atomix-cluster-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.tryToSend(AtomixClientTransportAdapter.java:159) ~[zeebe-transport-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.transport.impl.AtomixClientTransportAdapter.lambda$sendRequestInternal$2(AtomixClientTransportAdapter.java:88) ~[zeebe-transport-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:98) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:86) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:45) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:119) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:106) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:87) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:198) ~[zeebe-scheduler-8.2.0-SNAPSHOT.jar:8.2.0-SNAPSHOT]
"```

Seems to still occur in the most recent weekly benchmarks

**Comment by npepinpe** [comment] 2024-09-03 18:42
We made several improvements to DNS resolution. As this is old, I will close it in favor of new issues (if any).

**Closed by npepinpe** 2024-09-03 18:42 UTC
Labels: kind/bug, scope/broker, severity/low, scope/gateway, component/transport, component/zeebe
