### ISSUE TITLE
EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation is unstable

### ISSUE THREAD

**Issue by nicpuppa** [camunda/camunda#14971] opened 2023-11-02 14:11 UTC
**Summary**

- How often does the test fail? 1
- Does it block your work? 
- Do we suspect that it is a real failure? 

**Failures**

`EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation:144 Expected reference score is "450.000" got "334.123", deviation "25.751%" exceeds maximum allowed deviation "15.000%"`

**Logs**

Downloads complete logs from [here](https://drive.google.com/drive/folders/1R8X_FNT6siSQtIydy9voIv1XxJp_tVaZ)

**Comment by nicpuppa** [comment] 2023-11-06 07:15
Happened again:

```
Error:  Failures: 
Error:    EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation:144 Expected reference score is "450.000" got "371.068", deviation "17.540%" exceeds maximum allowed deviation "15.000%"
```

**Comment by npepinpe** [comment] 2023-11-15 12:14
@Zelldon - It's not clear to me why this fails. In theory, the only thing using the node at the time is the test, so the performance should be roughly equivalent across runs. 25% deviation is really a lot :thinking: 

We could switch it to be like the `LargeStateControllerPerformanceTest`, which just asserts that we're above some minimum threshold (whatever is acceptable). Unless you have an idea why it's sometimes so much slower, even though it runs alone and on a self-hosted runner? :thinking: I thought about cache contention with shared nodes, but this job should be using the whole node, right?

**Comment by korthout** [comment] 2023-11-15 14:40
@npepinpe Do I understand correctly that you're investigating this?

**Comment by npepinpe** [comment] 2023-11-15 14:41
Sort of :smile: Trying to get Chris involved ;)

**Comment by Zelldon** [comment] 2023-11-24 10:31
Failed again with: https://github.com/camunda/zeebe/actions/runs/6971982216/job/18973214307

```
[INFO] Running io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 332.7 s <<< FAILURE! -- in io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest
Error:  io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation(JMHTestCase) -- Time elapsed: 332.7 s <<< FAILURE!
java.lang.AssertionError: Expected reference score is "450.000" got "304.843", deviation "32.257%" exceeds maximum allowed deviation "15.000%"
	at io.camunda.zeebe.engine.perf.EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation(EngineLargeStatePerformanceTest.java:144)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```


On main when it succeeds https://github.com/camunda/zeebe/actions/runs/6979181397/job/18991962899
```
Benchmark                                                  Mode  Cnt   Score   Error  Units
LargeStateControllerPerformanceTest.measureStateRecovery  thrpt   25  13.583 ± 0.102  ops/s

Benchmark                                                     Mode  Cnt    Score   Error  Units
EngineLargeStatePerformanceTest.measureProcessExecutionTime  thrpt   50  509.332 ± 5.992  ops/s
```

or https://github.com/camunda/zeebe/actions/runs/6946211264
```
Benchmark                                                  Mode  Cnt   Score   Error  Units
LargeStateControllerPerformanceTest.measureStateRecovery  thrpt   25  12.388 ± 0.181  ops/s

Benchmark                                                     Mode  Cnt    Score   Error  Units
EngineLargeStatePerformanceTest.measureProcessExecutionTime  thrpt   50  431.323 ± 4.483  ops/s
```

How?!

**Comment by nicpuppa** [comment] 2023-12-01 08:25
Failed again on [https://github.com/camunda/zeebe/actions/runs/7057426514/job/19211087404?pr=15443](https://github.com/camunda/zeebe/actions/runs/7057426514/job/19211087404?pr=15443)

```
java.lang.AssertionError: Expected reference score is "450.000" got "522.296", deviation "16.066%" exceeds maximum allowed deviation "15.000%"
```

**Comment by ana-vinogradova-camunda** [comment] 2024-02-13 11:05
Happened again, but for backport to 8.3:

```
Error:  Failures: 
Error:    EngineLargeStatePerformanceTest.shouldProcessWithinExpectedDeviation:144 Expected reference score is "450.000" got "520.721", deviation "15.716%" exceeds maximum allowed deviation "15.000%"
```

Build link: [here](https://github.com/camunda/zeebe/actions/runs/7885292114/job/21516095570?pr=16318)

**Comment by korthout** [comment] 2024-06-03 12:23
Another time in [25731730569](https://github.com/camunda/camunda/actions/runs/9349739713/job/25731730569) for attempting to merge https://github.com/camunda/camunda/pull/18894#event-13020095018

>java.lang.AssertionError: Expected reference score is "450.000" got "528.414", deviation >"17.425%" exceeds maximum allowed deviation "15.000%"

**Comment by korthout** [comment] 2024-06-03 14:01
I was quickly looking into this, because it's blocking the merge of #18894 to `stable/8.3`.

> We could switch it to be like the `LargeStateControllerPerformanceTest`, which just asserts that we're above some minimum threshold (whatever is acceptable).

That doesn't appear to be the situation either though (1 >= x <= 1.2):
https://github.com/camunda/camunda/blob/c4078d88f52eca3915fc04540634394ab2cf2637/zeebe/broker/src/test/java/io/camunda/zeebe/broker/system/partitions/impl/perf/LargeStateControllerPerformanceTest.java#L78

@npepinpe Do you agree that I can safely apply the same assertion on 8.3? Typically hits just over 16-17% better performance

**Comment by npepinpe** [comment] 2024-06-04 07:43
Having a base threshold is probably fine :+1: We miss out on possible improvements followed by regressions, but I don't think it's worth the hassle here.

**Comment by korthout** [comment] 2024-06-04 08:55
Is a higher score a regression? That seems odd to me.

**Comment by npepinpe** [comment] 2024-06-04 08:58
No, I mean, we could have a new higher score for a while, and then introduce code that causes it to lower again (thus being a regression w.r.t. to the higher score), but not notice.

**Comment by nicpuppa** [comment] 2024-06-28 08:16
Hey @korthout do you think we can close this issue ?

**Comment by korthout** [comment] 2024-07-02 08:36
@nicpuppa It's unclear to whether we're still seeing this issue anymore. All comments from at least the last half year on this issue have been about 8.3, which we've made more lenient.

I'll close the issue for now. If someone encounters this issue again, please share details so we can investigate again.

**Comment by nicpuppa** [comment] 2024-08-23 10:19
Happened again: https://github.com/camunda/camunda/actions/runs/10523845954/job/29159410259

[Test results for Performance Tests (1).zip](https://github.com/user-attachments/files/16727313/Test.results.for.Performance.Tests.1.zip)

**Comment by megglos** [comment] 2024-09-09 13:17
it actually failed with:
```
java.lang.RuntimeException: org.openjdk.jmh.runner.RunnerException: No results returned
```
@Zelldon have you seen such an error yet?

would close this for now, until we see this more often

**Closed by megglos** 2024-09-09 13:17 UTC
Labels: kind/flake, component/zeebe, version:8.3.12, version:8.10.0-alpha5-rc1, version:8.10.0-alpha5, version:8.10.0-rc1

**Comment by Zelldon** [comment] 2024-09-09 14:20
> it actually failed with:
> ```
> java.lang.RuntimeException: org.openjdk.jmh.runner.RunnerException: No results returned
> ```
> @Zelldon have you seen such an error yet?
> 
> would close this for now, until we see this more often

Not that im aware
