### ISSUE TITLE
Benchmark worker does not re-establish broken connection to gateway

### ISSUE THREAD

**Issue by lenaschoenburg** [camunda/camunda#16296] opened 2024-02-09 13:07 UTC
Following some network issues and gateway restarts, our 8.1 release benchmark quickly degraded, apparently because the benchmark workers did not re-establish a broken connection. They remained running for several days, only logging the following:

> INFO: Received data on closed stream

It appears as if the connection was closed on the worker but the gateways were still sending data that way. We should revisit the benchmark worker reliability and connection management.

**Comment by megglos** [comment] 2024-02-19 10:38
ZDP-Planning:
- worth investigating soon as the impact in a real user application would be decrease or complete halt of processing throughput
- it's not clear if the cause if on client, worker or gateway side

**Comment by megglos** [comment] 2024-02-26 10:24
ZDP-Planning:
- keeping it once more, otherwise moving to backlog

**Comment by megglos** [comment] 2024-03-04 10:30
ZDP-Planning:
* moving to backlog as no capacity
* we could revisit if we see this happening more frequently and have user reports

**Comment by lenaschoenburg** [comment] 2024-06-03 11:59
I don't think I've seen it elsewhere. I think we can close this, if it happens again we'd have to start investigation from scratch anyway.

**Closed** 2024-06-03 12:01 UTC
Labels: kind/bug, severity/mid, area/reliability, area/test, impact/medium, likelihood/low, component/zeebe
