### ISSUE TITLE
Evaluate a good value for max append batch size

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#5473] opened 2020-10-05 08:39 UTC
**Description**

The [MAX_BATCH_SIZE](https://github.com/zeebe-io/zeebe/blob/develop/atomix/cluster/src/main/java/io/atomix/raft/roles/AbstractAppender.java#L54) is used to limit how many data is sent as a batch to a follower. Currently it is static and set to 32 kb. It is likely that this configure can help to improve the throughput. We should evaluate and benchmark different values to get an better understand how it impacts the performance and what would be a good value.

Ideally we add new metrics which show how many data is sent per append, to see whether the max batch size is really used or we have other limits already.

Blocked by https://github.com/zeebe-io/zeebe/issues/5472

**Comment by Zelldon** [comment] 2022-12-23 10:14
maybe also something we want to take a look at the hackweek

**Comment by megglos** [comment] 2023-01-20 10:48
relates to https://github.com/camunda/product-hub/issues/642
https://github.com/camunda/product-hub/issues/643

**Comment by megglos** [comment] 2023-02-17 10:38
It makes sense but we would only optimize for a certain setup e.g. our benchmark, this doesn't necessarily benefit users. User may still need to optimize for their setup.

**Comment by megglos** [comment] 2023-02-17 10:40
@falko do you have any input on this based on your experiences?

**Comment by entangled90** [comment] 2024-10-28 08:21
One round of benchmark done with the default 32 kb payload @ 150  PI/S, grafana link for all scenarios:
[Dashboard](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1729865725925&to=1729871502802&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-size&var-pod=cs-max-batch-size-zeebe-0&var-pod=cs-max-batch-size-zeebe-1&var-pod=cs-max-batch-size-zeebe-2&var-partition=All)

# Configurations timeline

##  max_appends=6, max_batch_size=64kb
```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=64kb --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark
```

- [X] started at 16:13
- [X] even partition distribution from 16:13
- [x] stopped at 16:36


## max_appends=6, max_batch_size=128kb

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=128KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark
```

- [x] started at 16:38
- [X] even partition distribution from 16:45
- [x] stopped at 17:00


## max_appends=6, max_batch_size=16kb

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=16KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark
```

- [x] started at 17:01
- [X] even partition distribution from 17:16
- [x] stopped at 17:27

## **DEFAULT** max_appends=6, max_batch_size=32kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=32KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark
```
 - [X] started at 17:30
 - [X] even partition distribution from 17:30
 - [X] stopped at  17:45

# Results
Backpressure and processing queue size improves with bigger batch sizes. All other metrics look stable (memory & GC as well). 
Messaging latency degrades a bit, but that's expected considering we are sending payloads 2x-4x bigger.

Smaller batch size (16KB) (even though the payload in this scenario 32KB) is the worst of all on many metric, even though I expected to behave similarly to 32KB because of the payload size. 

It may be fruitful to run the realistic benchmark as well with the configuration (32KB, 64KB, 128KB) as well.

Based on this benchmark configuration I would suggest to bump the default to 64KB or 128KB.

**Comment by entangled90** [comment] 2024-10-28 11:04
# Realistic benchmark scenario
[Grafana](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730105448000&to=1730111400000&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-size&var-pod=cs-max-batch-size-zeebe-0&var-pod=cs-max-batch-size-zeebe-1&var-pod=cs-max-batch-size-zeebe-2&var-partition=All)


## Configuration timeline
 Started on 28/10/2025 at 09:50:
```bash
helm install --create-namespace --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```
### **DEFAULT** max_appends=6, max_batch_size=32kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=32KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at  09:55
 - [X] even partition distribution from 10:01 
 - [X] stopped at  10:12

### max_appends=6, max_batch_size=64kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=64KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at 10:17 
 - [X] even partition distribution from 10:45 (took a lot!) 
 - [X] stopped at 11:00

### max_appends=6, max_batch_size=128kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendsPerFollower=6 --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=128KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at 11:00
 - [X] even partition distribution from  11:05
 - [X] stopped at 11:31


# Results
In this scenario as well bigger batch sizes seem to improve "Backpressure" & "Processing queue size". 
It also seems that more processes are completed (even if not by much):
![image](https://github.com/user-attachments/assets/055ef776-3f12-4add-98bc-e2d3c0ed9056)

Based on this benchmark configuration I would suggest to bump the default to 64KB or 128KB.

**Comment by entangled90** [comment] 2024-10-29 08:19
The above benchmark were run before this fix was added to the helm-charts: https://github.com/zeebe-io/benchmark-helm/pull/202

**Comment by entangled90** [comment] 2024-10-31 11:00
# REALISTIC SETUP run nr. 2
 Started on 30/10/2025 at 16:25:
[Dashboard](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730302200000&to=1730307600000&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-batch-size&var-pod=cs-batch-size-zeebe-0&var-pod=cs-batch-size-zeebe-1&var-pod=cs-batch-size-zeebe-2&var-partition=All)

```bash
helm install --create-namespace --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```
**NOTE**: maxAppendsPerFollower is not needed anymore, as it's now the default value.
## **DEFAULT** max_appends=6, max_batch_size=32kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=32KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at  16:25
 - [X] even partition distribution from 16:25 (but a broker restarted at 16:30) 
 - [X] stopped at 16:46 

## max_appends=6, max_batch_size=64kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=64KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at 16:52 
 - [X] even partition distribution from 17:00
 - [X] stopped at 17:15

## max_appends=6, max_batch_size=128kb :

```bash
helm upgrade --reuse-values --set zeebe.config.zeebe.broker.experimental.maxAppendBatchSize=128KB --namespace $BENCHMARK_NAME $BENCHMARK_NAME zeebe-benchmark/zeebe-benchmark -f values-realistic-benchmark.yaml
```

 - [X] started at 17:17
 - [X] even partition distribution from  17:30
 - [X] stopped at 18:06

# Results
Increasing the MAX_BATCH_SIZE increases the throughput by around 20%. This comes at the expense of increased latency (as expected) and more cpu usage, as it looks to be able to process more data.

Unfortunately, with the additional cpu usage the container starts throttling more frequently, exacerbating the latency degradation, so it would be better to see the results with more cpu dedicated how latency will behave.

For example, the  [Process instance execution time](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730302200000&to=1730307600000&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-batch-size&var-pod=cs-batch-size-zeebe-0&var-pod=cs-batch-size-zeebe-1&var-pod=cs-batch-size-zeebe-2&var-partition=All&viewPanel=132) increases a lot, even though the rate of process instance completed is higher than the baseline.

Another interesting metric is the [amount of data writte to disk](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730302200000&to=1730307600000&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-batch-size&var-pod=cs-batch-size-zeebe-0&var-pod=cs-batch-size-zeebe-1&var-pod=cs-batch-size-zeebe-2&var-partition=All&viewPanel=368), which looks much higher than before

:question:  Is the load on the system constant or does it depend on how much throughput zeebe is able to process?

If the latter is true, then we're not really comparing the same setup, so it's expected to see such different numbers.

:question: However, it still poses some questions on wether zeebe is handling the additional load *gracefully* or with a different behaviour (such as timing out instances?)

:thought_balloon:  If zeebe is behave correctly, probably increasing the buffer size to 64KB is sensible, while keeping in mind that in the future we may bump it to 128KB

**Comment by lenaschoenburg** [comment] 2024-10-31 11:08
None of these runs were able to complete process instances in time so I'd expect that there's an underlying issue that invalidates the benchmark results unfortunately.

![image](https://github.com/user-attachments/assets/26e074d3-0073-419e-8829-ee9b51b81273)

**Comment by entangled90** [comment] 2024-10-31 11:12
That's what I feared. The baseline as well was having the same issue (even more actually).

**Comment by entangled90** [comment] 2024-10-31 13:21
Thanks @Zelldon, I  was using an outdated version of the benchmark without your fix.

This time I've run them in parallel  in different namesapces `cs-max-batch-${batch-size}`

Here are the updated results:
-[Dashboard 32KB (Baseline)](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730376122830&to=1730379238215&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-32&var-pod=cs-max-batch-32-zeebe-0&var-pod=cs-max-batch-32-zeebe-1&var-pod=cs-max-batch-32-zeebe-2&var-partition=All)
- [Dashboard 64KB](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730376122830&to=1730379238215&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-64&var-pod=cs-max-batch-64-zeebe-0&var-pod=cs-max-batch-64-zeebe-1&var-pod=cs-max-batch-64-zeebe-2&var-partition=All)
- [Dashboard 128KB](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730376659657&to=1730379227489&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-128&var-pod=cs-max-batch-128-zeebe-0&var-pod=cs-max-batch-128-zeebe-1&var-pod=cs-max-batch-128-zeebe-2&var-partition=All)

I see that now the two rates are matched (50 PI/s per partition = 150) are handled in all three scenarios.
When the buffer size has been increased however I see that the number of [Job pushed & timedout is much higher](https://grafana.dev.zeebe.io/d/ce1xu7mewjpj4c/zeebe-temp-cs?orgId=1&from=1730376122830&to=1730379238215&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-64&var-pod=cs-max-batch-64-zeebe-0&var-pod=cs-max-batch-64-zeebe-1&var-pod=cs-max-batch-64-zeebe-2&var-partition=All&viewPanel=3).

:question: That may be related to the increased cpu usage & generally worse performance. Not sure if this is the cause or an effect of the increased cpu usage, but I wonder if we expected this metric to increase?

:question:  could be a situation when a timeout is now breached more frequently, causing an "avalanche" effect, adding more load, which then increases the number of timeouts?

**Comment by entangled90** [comment] 2024-11-05 12:37
After a review with @npepinpe we noticed that the  [Number of job push failed](https://github.com/camunda/camunda/issues/5473) is too high, even in the base case. 
It's probably better to reconfigure the workers' resources in order to make them able to handle the load (in the base case)

**Comment by entangled90** [comment] 2024-11-05 16:56
Benchmarks will be rerun after https://github.com/zeebe-io/benchmark-helm/pull/204 is merged

**Comment by Zelldon** [comment] 2024-11-05 17:56
> Benchmarks will be rerun after [zeebe-io/benchmark-helm#204](https://github.com/zeebe-io/benchmark-helm/pull/204) is merged

Make sure to create a new release first :)

**Comment by entangled90** [comment] 2024-11-06 09:28
Rerun the benchmarks:
- [Grafana 32KB (default)](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-batch-size-32&var-pod=cs-batch-size-32-zeebe-0&var-pod=cs-batch-size-32-zeebe-1&var-pod=cs-batch-size-32-zeebe-2&var-partition=All&from=1730818420188&to=1730821572427)
- [Grafana 64KB](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-64-take-2&var-pod=cs-max-batch-64-take-2-zeebe-0&var-pod=cs-max-batch-64-take-2-zeebe-1&var-pod=cs-max-batch-64-take-2-zeebe-2&var-partition=All&from=1730882621000&to=1730883480000)
- [Grafana 128KB](https://grafana.dev.zeebe.io/d/zeebe-dashboard/zeebe?orgId=1&var-DS_PROMETHEUS=prometheus&var-cluster=All&var-namespace=cs-max-batch-128&var-pod=cs-max-batch-128-zeebe-0&var-pod=cs-max-batch-128-zeebe-2&var-pod=cs-max-batch-128-zeebe-1&var-partition=All&from=1730878404413&to=1730881810384)

# Results
Benchmark are now much more stable.  Backpressure is almost always 0% for all configurations.
Observations:
- cpu usage increases slightly when increasing the buffer size.
  - 32KB: 1.08
  - 64KB: 1.12
  - 128KB: 1.20

  We may look into this as potentially bigger batches can be more "efficient" thus reducing cpu usage.

- Processing queue size greatly improves when using 128KB buffers, while there's not a noticeable difference between 32KB and 64KB
- Processing > number of records not exported: is almost zero with 128KB, while always greater than 0 in 32KB & 64KB configurations. On 64KB configuration looks worse. 
 The ElasticSearch Exporter flush duration is worse on the 64KB case compared to the other two. The cpu usage of the elastic search pod is worse.  
  :wrench:  My expectation would be that it should not be that different from the other two values (considering 64KB sits in between).
- Memory GC > Bigger batch sizes slitghtly increase the frequency and duration of GC. This is consistent with the increased cpu usage.

# Conclusion
In general I think bigger batches can improve performances with slight increases in cpu usage. 
I will repeat the test with 64KB as it looks strange.
 
:wrench: We may look into optimizing the cpu usage/memory allocation with bigger batches, to see if we can make it more efficient.

**Comment by npepinpe** [comment] 2024-11-07 10:11
Looking at overall processing throughput and processing latency, I did not really notice an improvement in any of the benchmarks compared to the baseline. That said, it's possible we aren't pushing enough load to see if there are any improvements on those metrics.

While we see an improvement in the processing queue size, this means it did not really translate to actual improvements for the user. I also couldn't confirm the "number of records not exported: is almost zero" part. It looks like it's still some? That would be a marked improvement for user, as it means less delay when it comes to seeing new data in the web apps.

![image](https://github.com/user-attachments/assets/73db9bbf-41a0-4c2a-a10d-935c3d451feb)

If we look at section 1, we see this is true - close to 0. But then section 2 shows the normal behavior. Are these separate runs?

**Comment by entangled90** [comment] 2024-11-07 10:16
No, they are the same run. I have tried to understand what happens at 09:10, but I could find an explanation.

Almost every metric has a dip at around 09:10:

![image](https://github.com/user-attachments/assets/e6dbf89a-03a6-4369-8e90-2e6c035d6679)

**Comment by entangled90** [comment] 2024-11-11 14:28
Given that improvements in the metrics are small and increase the cpu usage it's probably better to keep the current default value. It could possible that with a different workload a different value of this setting may be beneficial (if more cpu usage is ok for the customer for the customer example).

**Closed by entangled90** 2024-11-11 14:28 UTC
Labels: kind/toil, area/performance, component/raft, component/zeebe
