### ISSUE TITLE
Noticing heavy backpressure for hours even if current processed events is empty / low

### ISSUE THREAD

**Issue by ashprojects** [camunda/camunda#20177] opened 2024-07-09 15:10 UTC
**Describe the bug**
We are actively using Zeebe in production powering 15-20M PIs!
Our use case involves sending message corelation to move instances ahead. We generally send 1M messages to Zeebe from 16 workers every day once. Once message is published, the workflow at next step has a service task which after processing moves it back to a new message catch event.
We see it runs fine, but suddenly after finishing up probably 90% of work, something starts in Zeebe which results in 70-80% backpressure for some of the partitions. Job Created at that moment is also very less compared to previous hour.

We started processing from 10:00 AM.
At 12:10PM, we see processing was almost 90-95% complete, Zeebe backpressure kicks in which reduces the overall throughput of the system.
This is the current event detail during processind, when Zeebe is stable
![image](https://github.com/camunda/camunda/assets/15957226/21d71f62-1e69-4d72-8330-8ced49e89478)

This is after Zeebe looses stability, kicking backpressure, I can't see any major events hogging up the cluster
![image](https://github.com/camunda/camunda/assets/15957226/107bd38a-1132-426a-b804-b1f1109017c8)

gPRC request/sec was higher from 10-12PM but reduced with only Resource Exhausted later
![image](https://github.com/camunda/camunda/assets/15957226/cdb8e687-ddd7-4fe5-8098-0f7027a34d09)
![image](https://github.com/camunda/camunda/assets/15957226/cc5afd4f-f6fe-467f-9eaf-13bfbbe59324)

In Written Commands, I see JOB_BATCH.ACTIVATE command, at the time when Zeebe is not responding to Workers, for few hours. How is this possible?
![image](https://github.com/camunda/camunda/assets/15957226/35bbb3a7-6dca-4246-a9f2-60b81e7a855c)

In case of written events it is JOB.ACTIVATED events
![image](https://github.com/camunda/camunda/assets/15957226/5c62e862-156c-4abe-990e-8993912818f4)

Memory / CPU / Latency / PVC all seem not concerning
![image](https://github.com/camunda/camunda/assets/15957226/79fc9bad-bc6c-4504-bf0d-7b17238fdb6c)

**To Reproduce**
Not sure, looks like Zeebe is doing some internal processing that we are not aware of. We DON'T use Zeebe's own timers.
I do see spike in ES exporting during that time as well, but no huge latency.

**Expected behavior**

Backpressure should be explained.  Could be some backlog that Zeebe is processing asynchronous. It would be helpful to understand what that is, so we can avoid this downtime.

**Log/Stacktrace**

No ERRORs in logs found.
No rebalancing / role changes noticed as well during that time

**Environment:**
- OS: Linux
- Zeebe Version: 8.5.2
- Configuration:
1. ES exporters configured
2. Partitions: 16
3. Replica: 3
4. Brokers: 8 (Each having 2 leaders achieved during setup through /rebalance API)
5. Broker Size: 4vCPU 14GB Ram

**Comment by ashprojects** [comment] 2024-07-09 15:23
@korthout Apologies for mentioning you here. I have been a follower of Camunda, but we are facing this issue in production. 
I looked up for enterprise support for self-managed cluster, haven't got any response.
If you could help us debug + mitigate this here it would be very helpful.
Thanks in advance.

**Comment by korthout** [comment] 2024-07-10 11:57
Given the increase in JobBatch Activate commands, it could also be useful to investigate the workers configuration, specifically to check whether they correctly backoff on resource exhausted.

@ashprojects could you share:
- which client are you using? Different clients may implement backoff differently or not at all
- what configurations do you use for the job worker?
- whether you've set any custom backoff for the workers?

Note that my questions only aim to allow recovery on back pressure. The data requested by Deepthi concerns root cause analysis of why back pressure kicks in. It may be good to look into both, but resolving the root cause is more important.

**Comment by hanuhimanshu** [comment] 2024-07-10 12:27
Hi @deepthidevaki, here are the screenshots of the mertrics you asked

<img width="731" alt="image" src="https://github.com/camunda/camunda/assets/13232644/498646f1-a516-4893-8fc6-d716dbf10fe4">
<img width="1040" alt="image" src="https://github.com/camunda/camunda/assets/13232644/dd6f7fa9-963c-4b6e-a7d8-48ba38c8614a">
<img width="1451" alt="image" src="https://github.com/camunda/camunda/assets/13232644/541c556b-f9ec-4d9d-8e05-5e12f1aed6f9">
No Banned instances by partition

<img width="714" alt="image" src="https://github.com/camunda/camunda/assets/13232644/9d13f69a-3cd1-484b-8860-64383c0faf48">
<img width="725" alt="image" src="https://github.com/camunda/camunda/assets/13232644/28ae4b4e-7377-40c8-bc44-cadd2d0bd204">
 Scheduled command cache size is 0

<img width="723" alt="image" src="https://github.com/camunda/camunda/assets/13232644/0f0fdbb3-1bc5-471c-a1b8-2a194569fbe1">
<img width="1456" alt="image" src="https://github.com/camunda/camunda/assets/13232644/7cd2d356-a69e-439b-9704-1ca80ff5f147">
<img width="1456" alt="image" src="https://github.com/camunda/camunda/assets/13232644/ae48f6c4-5f0a-4f0d-8355-6586cfa4a73c">


1. We did not restart the broker, cluster recovered automatically
2. We did not observed this issue before. We used Zeebe 8.4 for a very brief period of time, that too on a relatively much smaller scale (less than 50K PIs).

**Comment by hanuhimanshu** [comment] 2024-07-10 13:01
Hi @korthout 

We are using [zeebe-node@8.3.1](https://www.npmjs.com/package/zeebe-node). Currently we have not set any custom backoff for the workers. we are creating a worker as follows
```
import {ZBClient, JOB_ACTION_ACKNOWLEDGEMENT} from "zeebe-node";

const client = new ZBClient({
	hostname: "hostname",
	useTLS: true,
	customSSL: {
	  rootCerts: `...cert`
	},
	connectionTolerance: 10000,
	port: "443"
});
client.createWorker({
    taskType: "topicName",
    timeout: Duration.seconds.of(300), // 5 mins for a timeout
    failProcessOnException: true,
    taskHandler: async (job, worker) => {
      ...process job. either return JOB_ACTION_ACKNOWLEDGEMENT of throw error if any
    }
});
```

**Comment by ashprojects** [comment] 2024-07-11 08:01
@korthout @deepthidevaki There is pattern which we have identified here:

We publish 1.5M messages slowly during 3-4 hours window every day, which move PIs ahead to a Service Task
This Service Task would make some DB calls, etc at application level. 
As per my observation, when all Service Tasks processing is near to completion (we can figure out from our DB as we do updates at this service task). This sudden heavy backpressure is noticed for an hour or less.

Today I saw this spike in "Replayed Events". What events is Zeebe replaying leading to backpressure?
![image](https://github.com/camunda/camunda/assets/15957226/d4c9428f-8e10-470f-bddb-db9b94ea3d1e)

It started at around 13:16 today, I see spike in "Skipped" commands on the partitions where backpressure is fired (in this case, which is Partition 3)
![image](https://github.com/camunda/camunda/assets/15957226/3dbe2efd-aaee-4423-ba3b-32fce021b997)

**Comment by ashprojects** [comment] 2024-07-15 09:59
@deepthidevaki More analysis at our end, 
1. Initially Job completion takes some time at our end job number of job completions to zeebe are lesser.
2. At the last, due to application logic, jobs become very small, so we complete the same type of job within few millis.

Theory: I think Zeebe is flooded with too many pending job completions and has to do some extra work to do some background processing before new jobs are delivered to clients. 

Another observation:
Memory usage is always above 80% in each broker even when there is no load. CPU on the other hand, once processing is done, comes back to <10%. Could there be any potential memory leak in Message Correlation, as our primary use case is that?

Shall I share a heap dump for further analysis as well?

**Comment by ashprojects** [comment] 2024-07-15 10:49
We started observing heavy backpressure from 13.36
![image](https://github.com/user-attachments/assets/d84ad323-a8f5-4485-bcdf-9dc7703f5a1b)

This is a screenshot from Latency.
I do see some slight increase in "Record Processing Duration".

However, there is some heavy activity in "Batch Event Processing" charts.

**Comment by deepthidevaki** [comment] 2024-07-17 07:47
The slight increase would have an overall higher impact. Which records have higher processing duration? I cannot see it from the graph.

**Comment by ashprojects** [comment] 2024-07-17 09:00
@deepthidevaki 
Sure,
When there was no backpressure
<img width="451" alt="image" src="https://github.com/user-attachments/assets/076367de-7c48-4d85-8670-5e3afe51d2c5">

When backpressure starting kicking in
<img width="1396" alt="image" src="https://github.com/user-attachments/assets/bff1dbff-651e-4cc5-bb13-19aabc556e7d">

<img width="382" alt="image" src="https://github.com/user-attachments/assets/db2cfd95-1d16-4f86-98db-9b1d34e89f68">


Kindly tell me if there's a better way to share if this is not meaningful.
Thanks

**Comment by remcowesterhoud** [comment] 2024-07-22 12:35
ZPA Triage:
- We are removing this from our board for now
- We see @deepthidevaki is somewhat driving it. If the problem becomes more clear it can be added to our board again.

**Comment by deepthidevaki** [comment] 2024-07-22 14:02
@ashprojects It seems job_batch.ACTIVATE commands get slower. As a result, generally the processor is able to process only less number of records per second (metrics Processing Per Partition). This also results in higher backpressure, because it is not able to process commands as fast as it was before. 

It is not clear why job_batch.ACTIVATE is getting slower. One hypothesis is
> Initially Job completion takes some time at our end job number of job completions to zeebe are lesser.

Because of this, there are many old jobs to be activated. This means they are not cached in memory (rocksdb) and they have to be read from the disk (rocksdb). By default, we allocate 500Mb for rocksdb per partitions. Since the snapshot size is > 500MB at this point, it is quite possible that it has to read from disk which adds extra latency. To verify this hypothesis, you could increase the memory allocated to rocksdb ( `ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MEMORYLIMIT`) and test your workload.

**Comment by ashprojects** [comment] 2024-07-26 12:55
@deepthidevaki Our memory % used by Zeebe already around 90% as mentioned above.
Increasing this `ZEEBE_BROKER_EXPERIMENTAL_ROCKSDB_MEMORYLIMIT` would need more memory increase for the pod? Currently it is allocated ~14GB.

**Comment by deepthidevaki** [comment] 2024-07-31 06:55
You would need a minimum memory of ROCKSDB_MEMORYLIMIT * number of partitions + java heap size + some extra for memory mapped journal segments.

**Comment by npepinpe** [comment] 2024-08-26 12:57
This issue seems stale. Is there anything more to do here, or should we close it?

**Comment by npepinpe** [comment] 2024-09-04 09:35
I will close it then.

**Closed by npepinpe** 2024-09-04 09:35 UTC
Labels: kind/bug, component/zeebe
