### ISSUE TITLE
Broken record compatibility with 8.3.x

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#14957] opened 2023-11-02 09:58 UTC
## Describe the bug

[It looks like we changed the ordering in our record protocol](https://github.com/camunda/zeebe/commit/5ca78d2e38ea81a878a74e88f886608973573f97) (which is based on SBE). SBE is in general ordering sensitive, see https://github.com/real-logic/simple-binary-encoding/wiki/FIX-SBE-XML-Primer#message-element

### Impact

Right now it seems that only the reading of BrokerVersion and RejectionType is affected, this might be right now not a huge issue, since we never act on rejections or check the version. TBH I haven't checked whether more is broken, this needs to be verified.

### Details 

The change causes problems in reading old record metadata, which I found during updating ZDB and writing tests for the serialization.

With the newest metadata (8.3.1) we got problems on versions 8.1 and 8.2:

1. The broker version can't be deserialized anymore, which causes it to read values like: `2303.512.4096`
2. The rejection type is not correctly read, causes to read values like: `INVALID_ARGUMENT` all the time

I checked the different classes and found the following:

```
8.3.1
Metadata 
  offset 60

VersionDecoder
 offset + 17

Rejection Type 
  offset + 31 = 91?


8.2.14

Metadata
  offset 60


Rejection Type
  offset + 17

VersionDecoder
  offset + 18
```

### Additional info

Check for more details in this [slack thread](https://camunda.slack.com/archives/C037W9NMATG/p1698909820592109)

**To Reproduce**

Run zdb tests you can see it or check the different class files, see comment https://github.com/camunda/zeebe/issues/14957#issuecomment-1790452740

You can see here when using different offsets we are able to read the Broker version:

![version](https://github.com/camunda/zeebe/assets/2758593/dd89faaa-9a14-4b3e-9d1e-75e671dd2c2c)

**Expected behavior**

We shouldn't rely on different projects to find such issues.

I expect we are finding such issues before we release, we should have appropriate tests for the serialization formats. Also covering different versions etc.

**Environment:**
- Zeebe Version: 8.3

**Comment by Zelldon** [comment] 2023-11-02 10:20
I extracted the java class files from the sources-jar of the different versions you can see the differences of the offsets




[831-RecordMetadataDecorder.txt](https://github.com/camunda/zeebe/files/13237499/831-RecordMetadataDecorder.txt)
[8215-RecordMetadataDecoder.txt](https://github.com/camunda/zeebe/files/13237500/8215-RecordMetadataDecoder.txt)


<details>

```diff
$ diff 8215-RecordMetadataDecoder.txt 831-RecordMetadataDecorder.txt 
15c15
<     public static final int BLOCK_LENGTH = 30;
---
>     public static final int BLOCK_LENGTH = 32;
18,19c18,19
<     public static final int SCHEMA_VERSION = 3;
<     public static final String SEMANTIC_VERSION = "8.2.15";
---
>     public static final int SCHEMA_VERSION = 4;
>     public static final String SEMANTIC_VERSION = "8.3.1";
425c425
<     public static int rejectionTypeId()
---
>     public static int brokerVersionId()
427c427
<         return 7;
---
>         return 9;
430c430
<     public static int rejectionTypeSinceVersion()
---
>     public static int brokerVersionSinceVersion()
432c432
<         return 0;
---
>         return 2;
435c435
<     public static int rejectionTypeEncodingOffset()
---
>     public static int brokerVersionEncodingOffset()
440c440
<     public static int rejectionTypeEncodingLength()
---
>     public static int brokerVersionEncodingLength()
442c442
<         return 1;
---
>         return 12;
445c445
<     public static String rejectionTypeMetaAttribute(final MetaAttribute metaAttribute)
---
>     public static String brokerVersionMetaAttribute(final MetaAttribute metaAttribute)
449c449
<             return "required";
---
>             return "optional";
455c455,457
<     public short rejectionTypeRaw()
---
>     private final VersionDecoder brokerVersion = new VersionDecoder();
> 
>     public VersionDecoder brokerVersion()
457c459,465
<         return ((short)(buffer.getByte(offset + 17) & 0xFF));
---
>         if (parentMessage.actingVersion < 2)
>         {
>             return null;
>         }
> 
>         brokerVersion.wrap(buffer, offset + 17);
>         return brokerVersion;
460c468
<     public RejectionType rejectionType()
---
>     public static int recordVersionId()
462c470
<         return RejectionType.get(((short)(buffer.getByte(offset + 17) & 0xFF)));
---
>         return 10;
464a473,476
>     public static int recordVersionSinceVersion()
>     {
>         return 3;
>     }
466c478
<     public static int brokerVersionId()
---
>     public static int recordVersionEncodingOffset()
468c480
<         return 9;
---
>         return 29;
471c483
<     public static int brokerVersionSinceVersion()
---
>     public static int recordVersionEncodingLength()
476c488,498
<     public static int brokerVersionEncodingOffset()
---
>     public static String recordVersionMetaAttribute(final MetaAttribute metaAttribute)
>     {
>         if (MetaAttribute.PRESENCE == metaAttribute)
>         {
>             return "optional";
>         }
> 
>         return "";
>     }
> 
>     public static int recordVersionNullValue()
478c500
<         return 18;
---
>         return 65535;
481c503
<     public static int brokerVersionEncodingLength()
---
>     public static int recordVersionMinValue()
483c505
<         return 12;
---
>         return 0;
486c508
<     public static String brokerVersionMetaAttribute(final MetaAttribute metaAttribute)
---
>     public static int recordVersionMaxValue()
488c510,515
<         if (MetaAttribute.PRESENCE == metaAttribute)
---
>         return 65534;
>     }
> 
>     public int recordVersion()
>     {
>         if (parentMessage.actingVersion < 3)
490c517
<             return "optional";
---
>             return 65535;
493c520
<         return "";
---
>         return (buffer.getShort(offset + 29, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF);
496d522
<     private final VersionDecoder brokerVersion = new VersionDecoder();
498c524
<     public VersionDecoder brokerVersion()
---
>     public static int rejectionTypeId()
500c526,546
<         if (parentMessage.actingVersion < 2)
---
>         return 7;
>     }
> 
>     public static int rejectionTypeSinceVersion()
>     {
>         return 0;
>     }
> 
>     public static int rejectionTypeEncodingOffset()
>     {
>         return 31;
>     }
> 
>     public static int rejectionTypeEncodingLength()
>     {
>         return 1;
>     }
> 
>     public static String rejectionTypeMetaAttribute(final MetaAttribute metaAttribute)
>     {
>         if (MetaAttribute.PRESENCE == metaAttribute)
502c548
<             return null;
---
>             return "required";
505,506c551,561
<         brokerVersion.wrap(buffer, offset + 18);
<         return brokerVersion;
---
>         return "";
>     }
> 
>     public short rejectionTypeRaw()
>     {
>         return ((short)(buffer.getByte(offset + 31) & 0xFF));
>     }
> 
>     public RejectionType rejectionType()
>     {
>         return RejectionType.get(((short)(buffer.getByte(offset + 31) & 0xFF)));
508a564
> 
606a663,791
>     public static int authorizationId()
>     {
>         return 11;
>     }
> 
>     public static int authorizationSinceVersion()
>     {
>         return 4;
>     }
> 
>     public static String authorizationCharacterEncoding()
>     {
>         return java.nio.charset.StandardCharsets.UTF_8.name();
>     }
> 
>     public static String authorizationMetaAttribute(final MetaAttribute metaAttribute)
>     {
>         if (MetaAttribute.PRESENCE == metaAttribute)
>         {
>             return "required";
>         }
> 
>         return "";
>     }
> 
>     public static int authorizationHeaderLength()
>     {
>         return 4;
>     }
> 
>     public int authorizationLength()
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             return 0;
>         }
> 
>         final int limit = parentMessage.limit();
>         return (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>     }
> 
>     public int skipAuthorization()
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             return 0;
>         }
> 
>         final int headerLength = 4;
>         final int limit = parentMessage.limit();
>         final int dataLength = (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>         final int dataOffset = limit + headerLength;
>         parentMessage.limit(dataOffset + dataLength);
> 
>         return dataLength;
>     }
> 
>     public int getAuthorization(final MutableDirectBuffer dst, final int dstOffset, final int length)
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             return 0;
>         }
> 
>         final int headerLength = 4;
>         final int limit = parentMessage.limit();
>         final int dataLength = (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>         final int bytesCopied = Math.min(length, dataLength);
>         parentMessage.limit(limit + headerLength + dataLength);
>         buffer.getBytes(limit + headerLength, dst, dstOffset, bytesCopied);
> 
>         return bytesCopied;
>     }
> 
>     public int getAuthorization(final byte[] dst, final int dstOffset, final int length)
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             return 0;
>         }
> 
>         final int headerLength = 4;
>         final int limit = parentMessage.limit();
>         final int dataLength = (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>         final int bytesCopied = Math.min(length, dataLength);
>         parentMessage.limit(limit + headerLength + dataLength);
>         buffer.getBytes(limit + headerLength, dst, dstOffset, bytesCopied);
> 
>         return bytesCopied;
>     }
> 
>     public void wrapAuthorization(final DirectBuffer wrapBuffer)
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             wrapBuffer.wrap(buffer, offset, 0);
>             return;
>         }
> 
>         final int headerLength = 4;
>         final int limit = parentMessage.limit();
>         final int dataLength = (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>         parentMessage.limit(limit + headerLength + dataLength);
>         wrapBuffer.wrap(buffer, limit + headerLength, dataLength);
>     }
> 
>     public String authorization()
>     {
>         if (parentMessage.actingVersion < 4)
>         {
>             return "";
>         }
> 
>         final int headerLength = 4;
>         final int limit = parentMessage.limit();
>         final int dataLength = (int)(buffer.getInt(limit, java.nio.ByteOrder.LITTLE_ENDIAN) & 0xFFFF_FFFFL);
>         parentMessage.limit(limit + headerLength + dataLength);
> 
>         if (0 == dataLength)
>         {
>             return "";
>         }
> 
>         final byte[] tmp = new byte[dataLength];
>         buffer.getBytes(limit + headerLength, tmp, 0, dataLength);
> 
>         return new String(tmp, java.nio.charset.StandardCharsets.UTF_8);
>     }
> 
666,668d850
<         builder.append("rejectionType=");
<         builder.append(this.rejectionType());
<         builder.append('|');
679a862,867
>         builder.append("recordVersion=");
>         builder.append(this.recordVersion());
>         builder.append('|');
>         builder.append("rejectionType=");
>         builder.append(this.rejectionType());
>         builder.append('|');
681a870,872
>         builder.append('|');
>         builder.append("authorization=");
>         builder.append('\'').append(authorization()).append('\'');
691a883
>         skipAuthorization();

```

</details>

**Comment by koevskinikola** [comment] 2023-11-08 14:37
ZPA triage:
- Reverting this change might cause further issues with record compatibility. We need to investigate more how many of the fields are impacted.
- We should reproduce and test this in our upgrade tests. This will allow us to better investigate and determine the full size of the impact of this issue.
- Priority is `upcoming` as we need to fix this before more users start reporting this.
- Size is `large` as we are not aware of how much time we would need to invest in testing and coming up with a good solution of this bug.
- We should increase our test coverage for our SBE messages/binary compatibility so we avoid problems like this one in the future.

**Comment by abbasadel** [comment] 2023-11-27 13:49
ZPA Planning:
* No plans to work on this issue this iteration

**Comment by korthout** [comment] 2023-11-27 13:50
Some additional context:
- fixing this would likely break compatibility again, do we really want to cause such a problem?
- improving our test coverage is important, but we're focused on other efforts first

**Comment by megglos** [comment] 2024-04-03 07:20
@oleschoenburg given your work on the rolling update support, is this something we have handled or would be able to detect further on with the new update tests?

**Comment by oleschoenburg** [comment] 2024-04-03 07:23
It's possible that we'd now catch it through the update tests but I'm not quite sure about that. I think it would still make sense to add explicit tests that would guard against breaking changes in the SBE protocol.

**Comment by megglos** [comment] 2024-04-23 10:26
k, I would create a new issue for us to setup tests that verify there are no incompatible changes to the protocol

**Comment by npepinpe** [comment] 2024-05-29 13:15
I will create an issue to address the testing improvements, and we can close this: we won't fix this because changing it again would break backwards compat for more supported versions than not.

**Comment by npepinpe** [comment] 2024-05-29 13:18
Superseded by: https://github.com/camunda/camunda/issues/18932

**Closed by npepinpe** 2024-05-29 13:18 UTC
Labels: kind/bug, severity/high, BREAKING CHANGE, component/protocol, component/zeebe
