### ISSUE TITLE
[stable/8.3] `AtomixTransportTest.shouldRetryAndSucceedAfterResponseIsValid` is flaky

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#19031] opened 2024-06-03 13:28 UTC
**Summary**

- Workflow run: https://github.com/camunda/camunda/actions/runs/9350083880/job/25732796035
- Occurred trying to merge: https://github.com/camunda/camunda/pull/18894#event-13020483899

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
Error:  Tests run: 24, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.09 s <<< FAILURE! -- in io.camunda.zeebe.transport.impl.AtomixTransportTest
Error:  io.camunda.zeebe.transport.impl.AtomixTransportTest.shouldRetryAndSucceedAfterResponseIsValid[use different messaging service] -- Time elapsed: 7.506 s <<< ERROR!
java.util.concurrent.ExecutionException: Connection RemoteClientConnection{channel=[id: 0x3106b57e, L:/127.0.0.1:58146 ! R:localhost/127.0.0.1:2026]} was closed
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:145)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:112)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:201)
	at io.camunda.zeebe.transport.impl.AtomixTransportTest.shouldRetryAndSucceedAfterResponseIsValid(AtomixTransportTest.java:316)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: io.atomix.cluster.messaging.MessagingException$ConnectionClosed: Connection RemoteClientConnection{channel=[id: 0x3106b57e, L:/127.0.0.1:58146 ! R:localhost/127.0.0.1:2026]} was closed
	at io.atomix.cluster.messaging.impl.AbstractClientConnection.close(AbstractClientConnection.java:76)
	at io.atomix.cluster.messaging.impl.NettyMessagingService.lambda$getOrCreateClientConnection$36(NettyMessagingService.java:675)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1161)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:753)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:729)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:619)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1349)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:755)
	at io.netty.channel.AbstractChannelHandlerContext.access$1200(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$11.run(AbstractChannelHandlerContext.java:738)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:840)
</pre>
</details>

**Hypotheses**

There are several old issues reporting similar problems, but these are closed:
- https://github.com/camunda/camunda/issues/3703
- https://github.com/camunda/camunda/issues/3603
- https://github.com/camunda/camunda/issues/4124
- https://github.com/camunda/camunda/issues/4911
- https://github.com/camunda/camunda/issues/5101

**Logs**

- https://drive.google.com/drive/folders/1hv0Iv3lai_shbDPl31TTuHxlHKW15Spa?usp=drive_link

**Comment by rodrigo-lourenco-lopes** [comment] 2024-07-10 08:42
I tried to run the same test locally hundreds of times and was not able to reproduce it.

It seems to be somewhat different from the other cases, in which there were race conditions, while on these the request was sent and failed because the client connection had already been closed. Likely some issue lead to the closure of this.

I would close this for now since it has only happened once and reopen it in case it happens again.

**Closed by rodrigo-lourenco-lopes** 2024-07-10 08:42 UTC
Labels: kind/flake, component/zeebe
