### ISSUE TITLE
Process with execution listener will not be shown in process instance list

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#25433] opened 2024-11-28 14:50 UTC
### Description (required on creation)

Processes with execution listener are shown in main screen (statistics - http://localhost:8080/operate) but not in process instances list (http://localhost:8080/operate/processes?incidents=true&active=true&completed=true&canceled=true)

### Steps to reproduce (required on creation)

1. Start Elasticsearch (docker-compose up elasticsearch)
2. Start Camunda 8.6.4 with

```shell
CAMUNDA_OPERATE_CSRF_PREVENTION_ENABLED=false
SPRING_PROFILES_ACTIVE=broker,operate,tasklist,auth
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://localhost:9200/
ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
```

3. Access Operate (http://localhost:8080/operate)
4. Deploy provided `demoProcess.bpmn` and `demoProcess2.bpmn` ([demo-bpmn-files.zip](https://github.com/user-attachments/files/17958881/demo-bpmn-files.zip)) 

```shell
zbctl --insecure deploy demoProcess.bpmn
zbctl --insecure deploy demoProcess2.bpmn
```
4. Start both processes (use the processDefinitionKey from zbctl output) by

```shell
zbctl --insecure create instance 2251799813685250 
zbctl --insecure create instance 2251799813685252
```
6. Check in Operate if 2 processes exists:

In start screen it shows 2 processes: http://localhost:8080/operate
but not in processes list:
http://localhost:8080/operate/processes?incidents=true&active=true&completed=true&canceled=true (edited) 

The second process instance is stored as activity (see field `processInstanceKey`, `key` and `joinRelation.parent`:
```json
{
  "id": "2251799813685259",
  "key": 2251799813685259,
  "partitionId": 1,
  "processInstanceKey": 2251799813685259,
  "activityId": "DemoProcess2",
  "activityState": null,
  "activityType": null,
  "errorMessage": null,
  "incident": false,
  "jobFailedWithRetriesLeft": false,
  "tenantId": "<default>",
  "position": 25,
  "positionIncident": null,
  "positionJob": 26,
  "joinRelation": {
    "name": "activity",
    "parent": 2251799813685259
  },
  "processName": "DemoProcess2",
  "bpmnProcessId": "DemoProcess2",
  "state": "ACTIVE",
  "processVersion": 1,
  "startDate": "2024-11-28T13:42:38.392+0000",
  "processDefinitionKey": 2251799813685252
}
```

### Current behavior (required on creation)

* Process instances with execution listener will not be shown

### Expected behavior (required on creation)

* Process instances with execution listener will be shown 

### Environment (required on creation)

Any

### Rootcause (required on prioritization)
See point 6 in "Steps to reproduce"

### Additional context
Seen in [Support 24703](https://jira.camunda.com/browse/SUPPORT-24703)

### Handover Dev to QA (required before manual testing)

- Resources:
  
- Versions to validate:
  
- Release version (in which version this feature will be released)
  

### Links

```[tasklist]
### Pull Requests
```

**Comment by ralfpuchert** [comment] 2024-11-29 12:04
[demo-bpmn-files.zip](https://github.com/user-attachments/files/17958881/demo-bpmn-files.zip)

**Comment by ThorbenLindhauer** [comment] 2024-12-05 13:19
@ralfpuchert is this a duplicate of https://github.com/camunda/camunda/issues/24744?

**Comment by ralfpuchert** [comment] 2024-12-06 08:36
@ThorbenLindhauer Yes, it is the same behavior.

**Comment by ThorbenLindhauer** [comment] 2024-12-06 18:30
Closing as duplicate of https://github.com/camunda/camunda/issues/24744

**Closed by ThorbenLindhauer** 2024-12-06 18:30 UTC
Labels: kind/bug, support, component/operate, component/backend, version:8.6.4
