### ISSUE TITLE
LogStorageAppender was closed before opening

### ISSUE THREAD

**Issue by saig0** [camunda/camunda#8757] opened 2022-02-10 05:19 UTC
**Description**

The following message is logged as a failure:

```
io.camunda.zeebe.logstreams.impl.log.LogStreamImpl$LogStorageAppenderClosedException: 
  LogStorageAppender was closed before opening
```

<details><summary>Full Stacktrace</summary>
 <p>

```
io.camunda.zeebe.logstreams.impl.log.LogStreamImpl$LogStorageAppenderClosedException: LogStorageAppender was closed before opening succeeded

at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.closeAppender ( [io/camunda.zeebe.logstreams.impl.log/LogStreamImpl.java:265](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.logstreams.impl.log%2FLogStreamImpl.java&line=265&project=zeebe-io) )
at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.lambda$closeAsync$1 ( [io/camunda.zeebe.logstreams.impl.log/LogStreamImpl.java:128](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.logstreams.impl.log%2FLogStreamImpl.java&line=128&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorJob.invoke ( [io/camunda.zeebe.util.sched/ActorJob.java:79](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorJob.java&line=79&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorJob.execute ( [io/camunda.zeebe.util.sched/ActorJob.java:44](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorJob.java&line=44&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorTask.execute ( [io/camunda.zeebe.util.sched/ActorTask.java:122](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorTask.java&line=122&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask ( [io/camunda.zeebe.util.sched/ActorThread.java:97](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=97&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorThread.doWork ( [io/camunda.zeebe.util.sched/ActorThread.java:80](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=80&project=zeebe-io) )
at io.camunda.zeebe.util.sched.ActorThread.run ( [io/camunda.zeebe.util.sched/ActorThread.java:189](https://console.cloud.google.com/debug?referrer=fromlog&file=io%2Fcamunda.zeebe.util.sched%2FActorThread.java&line=189&project=zeebe-io) )
```

</p>
</details>

The message is logged after a partition transitioned to `LEADER` and back to `FOLLOWER` in a short time (< 1s). 

However, the broker was able to transition to `FOLLOWER` successfully. We can consider the log statement as noise and should omit it.  

[Log](https://console.cloud.google.com/logs/query;query=%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.namespace_name%3D%22medic-cw-05-6bb8c35e1c-benchmark%22%0Aresource.labels.pod_name%3D%22medic-cw-05-6bb8c35e1c-benchmark-zeebe-1%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.container_name%3D%22zeebe-cluster-helm%22%0Aresource.labels.project_id%3D%22zeebe-io%22;timeRange=2022-02-09T23:13:04.641Z%2F2022-02-10T00:13:04.641Z;pinnedLogId=2022-02-09T23:42:34.641805946Z%2F5xibcpdwp0tnk3ua;summaryFields=resource%252Flabels%252Fpod_name,jsonPayload%252Fcontext%252FpartitionId:false:32:beginning:false;cursorTimestamp=2022-02-09T23:42:34.643791417Z?project=zeebe-io)

**Environment:**
- Zeebe Version: `1.4.0-SNAPSHOT`

**Comment by npepinpe** [comment] 2022-02-15 08:56
Please verify whether this is an expected error or not. If it is an expected case, then we should handle it and no exception should bubble up.

**Comment by saig0** [comment] 2022-02-17 10:31
@npepinpe I see no reason to print this error message. At the moment, the log storage appender just assumes that it should be opened before it can be closed. But it works also in this way.

**Comment by deepthidevaki** [comment] 2022-10-31 13:03
This happened again in 8.2.0-SNAPSHOT.

[logs](https://console.cloud.google.com/logs/query;cursorTimestamp=2022-10-28T13:07:21.766713451Z;pinnedLogId=2022-10-28T13:07:21.766713451Z%2Fgf1wuls4ljbfehv0;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-d%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22%0Aresource.labels.cluster_name%3D%22ultrachaos%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%22aba6a5e0-3bc3-4ba8-8390-a323bfb67d94-zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-2%22%0Atimestamp%3D%222022-10-28T13:07:21.766713451Z%22%0AinsertId%3D%22gf1wuls4ljbfehv0%22;timeRange=2022-10-28T12:37:51.767Z%2F2022-10-28T13:37:51.767Z?project=camunda-cloud-240911)

This occured in CommandApiHandler when trying to create a writer. The root cause is the order in which we notifies PartitionListeners.  We do it in the following order

transitionToLeader:
1. Install service LogStream
2. Install other services
3. Install completed
4. Notify PartitionListener.onBecomingLeader
transitionToFollower:
1. Close other services
2. Close service LogStream
3. Install follower services
4. transition completed
5. Notify PartitionListener.onBecomingFollower 

Here the problem is that CommandAPIHandler depends on installed services LogStream to open the writer. But it is already closed. So it logs an error. If the CommandApu was before transitioning from leader to follower, then this error can be prevented.

**Comment by koevskinikola** [comment] 2023-06-14 12:22
This occured again on `8.2.5` ([internal logs link](https://console.cloud.google.com/logs/query;query=error_group%2528%22CL_d4oLLivyibQ%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22camunda-saas-int%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.namespace_name%3D%227bc8310a-8279-4097-9473-ddaad847d33d-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-3%22%0Aresource.labels.location%3D%22europe-north1%22%0Aresource.labels.pod_name%3D%22zeebe-0%22;timeRange=2023-06-13T13:27:08.047Z%2F2023-06-13T14:27:08.047Z;cursorTimestamp=Tue%20Jun%2013%202023%2015:57:08%20GMT%2B0200%20%28Central%20European%20Summer%20Time%29?project=camunda-saas-int)).

**Comment by berkaycanbc** [comment] 2023-06-15 12:28
This occurred again on `8.3.0-alpha2-loop-no-more` ([internal log](https://console.cloud.google.com/logs/query;query=error_group%2528%22CL_d4oLLivyibQ%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.namespace_name%3D%222cd6bad0-dba0-4f1d-99d6-1ee92e8f2329-zeebe%22%0Aresource.labels.cluster_name%3D%22worker-5%22%0Aresource.labels.project_id%3D%22camunda-saas-prod%22%0Aresource.labels.location%3D%22northamerica-northeast2%22;timeRange=2023-06-14T18:12:38.492Z%2F2023-06-14T19:12:38.492Z;cursorTimestamp=2023-06-14T18:42:08.492004849Z?project=camunda-saas-prod))

**Comment by npepinpe** [comment] 2024-09-03 19:15
I think we can close this, we don't open the appender anymore - it's just there ;)

**Closed by npepinpe** 2024-09-03 19:15 UTC
Labels: kind/toil, scope/broker, component/partition-transitions, component/zeebe
