### ISSUE TITLE
Index outOfBounds while fetching next snapshot of removed member.

### ISSUE THREAD

**Issue by rodrigo-lourenco-lopes** [camunda/camunda#19642] opened 2024-06-21 14:10 UTC
**Describe the bug**
We observed the following error message in the logs:

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at io.camunda.zeebe.snapshots.impl.FileBasedSnapshotChunkReader.seek(FileBasedSnapshotChunkReader.java:83) ~[zeebe-snapshots-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderAppender.buildInstallRequest(LeaderAppender.java:407) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderAppender.replicateSnapshot(LeaderAppender.java:910) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderAppender.tryToReplicate(LeaderAppender.java:877) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:786) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderAppender.appendEntries(LeaderAppender.java:610) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.raft.roles.LeaderRole.appendMembers(LeaderRole.java:411) ~[zeebe-atomix-cluster-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.atomix.utils.concurrent.SingleThreadContext$WrappedRunnable.run(SingleThreadContext.java:178) ~[zeebe-atomix-utils-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```
This happened after failing to probe member 2 and removing this, followed to several warnings of failing to sent a message to the member 2. After the error, the partition 1 to became unhealthy.

Following the stack trace it seems that we are trying to fetch the next snapshot of a member that we no longer have.

**To Reproduce**

Unclear. 

**Expected behavior**

No failure occurred. 

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

</p>
</details>

[Logs 20240621 160430.json](https://github.com/user-attachments/files/15928702/Logs.20240621.160430.json)

[Errror group](https://console.cloud.google.com/errors/detail/CM_f0ebPwp3RDQ;service=zeebe;time=P7D?project=camunda-saas-int-chaos)

**Environment:**
- OS: 
- Zeebe Version: 8.6.0-SNAPSHOT
- Configuration: G3_S_HA

**Comment by korthout** [comment] 2024-06-24 12:25
@rodrigo-lourenco-lopes Is ZPA expected to do something for this? It seems like a ZDP issue to me

**Comment by koevskinikola** [comment] 2024-06-25 07:55
Issue occurred again:
* Medic benchmark 2024-cw-26
* [GCP logs (downloaded)](https://drive.google.com/file/d/16FH2y51sfPN1hhXq-nfilHXK9Nrv2A74/view?usp=sharing)
* [GCP logs (link)](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.pod_name%3D%22medic-y-2024-cw-26-e480488-benchmark-zeebe-1%22%0Aresource.labels.namespace_name%3D%22medic-y-2024-cw-26-e480488-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe%22;pinnedLogId=2024-06-24T19:57:15.671875800Z%2Fw6trpfby7zwkyjol;cursorTimestamp=2024-06-24T19:59:34.442187583Z;startTime=2024-06-24T19:27:45.671Z;endTime=2024-06-24T20:27:45.671Z?project=zeebe-io)

**Comment by lenaschoenburg** [comment] 2024-06-25 07:56
@EuroLew maybe something you could look into? Could be related to recent changes.

**Comment by EuroLew** [comment] 2024-06-25 17:55
So far:

It appears that the snapshot is persisted, that is all the chunks have been processed and the last chunk we see that [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-06-24T19:57:23.297693584Z;endTime=2024-06-24T22:27:45.671Z;pinnedLogId=2024-06-24T19:57:15.671875800Z%2Fw6trpfby7zwkyjol;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.pod_name%3D%22medic-y-2024-cw-26-e480488-benchmark-zeebe-1%22%0Aresource.labels.namespace_name%3D%22medic-y-2024-cw-26-e480488-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aseverity%3E%3DDEFAULT%0ASEARCH%2528%2213730922%22%2529%0Atimestamp%3D%222024-06-24T19:57:11.298248530Z%22%0AinsertId%3D%220mvq4pwzsg4b8it3%22;startTime=2024-06-24T18:27:45.671Z?project=zeebe-io) and given that it is a log from the follower we know the `complete` field must have been true so according to the view of the follower it received the last chunk.

However it appears that the leader still attempts to send another chunk? [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-06-24T19:57:15.666831959Z;endTime=2024-06-24T22:27:45.671Z;pinnedLogId=2024-06-24T19:57:15.671875800Z%2Fw6trpfby7zwkyjol;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.pod_name%3D%22medic-y-2024-cw-26-e480488-benchmark-zeebe-1%22%0Aresource.labels.namespace_name%3D%22medic-y-2024-cw-26-e480488-benchmark%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aseverity%3E%3DDEFAULT%0ASEARCH%2528%2213730922%22%2529%0Atimestamp%3D%222024-06-24T19:57:15.666831959Z%22%0AinsertId%3D%22xux17ikr28p4yr58%22;startTime=2024-06-24T18:27:45.671Z?project=zeebe-io) which failed, the `complete` field for this "extra" chunk is true. So my assumption is that it is sending duplicate final chunks.

**Comment by EuroLew** [comment] 2024-06-26 13:53
The issue is occurs when the last snapshot chunk timeouts and it attempts to send the same chunk again, as the name of the last file to seek to (for the retry) is contained inside a `ByteBuffer` it gets read for the first initial attempt but then the position is at the end of the buffer and it seeks to an empty string `""` resulting in the index out of bounds issue. To fix this simply ensure that each time we seek to a given file name we `clear()` the buffer afterwards so retries are successful. This was fixed with the addition of the `SnapshotChunkid` class [here](https://github.com/camunda/camunda/pull/19490/files#diff-fd93d134d15b234139c1247e462a6f66cc66bc91a1c97aa380c24381e227565a) which adds an explicit `clear()` everytime the buffer is read from. 

A PR has been added which applies the same fix for the `toString()` call to avoid any issues with trying to retrieve an ID after logging its string representation and a test to ensure `seek` always obeys this buffer idempotency.

https://github.com/camunda/camunda/pull/19795

**Closed** 2024-06-27 08:30 UTC
Labels: kind/toil, component/zeebe
