### ISSUE TITLE
Flaky `zbctl` test `update_job_timeout`

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#15699] opened 2023-12-21 15:16 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
   - Only once so far 
- Does it block your work?
   - No 
- Do we suspect that it is a real failure?
   - No

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands
    main_test.go:386: update job timeout: diff (-want +got):
          []string{
        - 	"Updated the timeout of job with key '2251799813685359' to '10000'",
        + 	"Error: rpc error: code = NotFound desc = Command 'UPDATE_TIMEOUT' rejected with code 'NOT_FOUND': Expected to update job deadline with key '2251799813685371', but no such job was found",
          	"",
          }
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands/update_job_timeout
    testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
</pre>
</details>

**Hypotheses**

It looks like for each test case the same job ID is always generated. However, it might be that the job ID has changed for this particular test for some reason (need to investigate). To check what job ID is currently being generated the test can be run locally:

- Run `strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 1")` command for `update job timeout` test case. The generated job ID can be found in the output. Example:

```
{
	name: "update job timeout",
	setupCmds: [][]string{
			strings.Fields("--insecure deploy resource testdata/job_model.bpmn"),
			strings.Fields("--insecure create instance jobProcess"),
			//strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 1"),
	},
	//cmd:        strings.Fields("--insecure update timeout 2251799813685371 --timeout 10000"),
        cmd:        strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 1"),
	goldenFile: "testdata/update_job_timeout.golden",
}
```

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

<details><summary>Logs</summary>
<pre>
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands
    main_test.go:386: update job timeout: diff (-want +got):
          []string{
        - 	"Updated the timeout of job with key '2251799813685359' to '10000'",
        + 	"Error: rpc error: code = NotFound desc = Command 'UPDATE_TIMEOUT' rejected with code 'NOT_FOUND': Expected to update job deadline with key '2251799813685371', but no such job was found",
          	"",
          }
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands/update_job_timeout
    testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
</pre>
</details>

**Comment by abbasadel** [comment] 2023-12-21 16:08
Nice catch @koevskinikola.

**Comment by berkaycanbc** [comment] 2023-12-28 09:27
Occurred again: https://github.com/camunda/zeebe/actions/runs/7342702660/job/19992277133#step:6:55

<details><summary>Assertion error</summary>
<pre>
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands
    main_test.go:386: update job timeout: diff (-want +got):
          []string{
        - 	"Updated the timeout of job with key '2251799813685359' to '10000'",
        + 	"Error: rpc error: code = NotFound desc = Command 'UPDATE_TIMEOUT' rejected with code 'NOT_FOUND': Expected to update job deadline with key '2251799813685371', but no such job was found",
          	"",
          }
=== CONT  TestZbctlWithInsecureGateway/TestCommonCommands/update_job_timeout
    testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
</pre>
</details>

**Comment by korthout** [comment] 2024-01-03 17:23
I've had a look at this. This is a race condition where Zeebe has not yet processed the created process instance far enough to have the job available for activation/updateTimeout by the time the `zbctl --insecure update timeout 2251799813685371 --timeout 10000` command is executed.

```go
{
	name: "update job timeout",
	setupCmds: [][]string{
		strings.Fields("--insecure deploy resource testdata/job_model.bpmn"),
		strings.Fields("--insecure create instance jobProcess"),
		strings.Fields("--insecure activate jobs jobType --maxJobsToActivate 1"),
	},
	cmd:        strings.Fields("--insecure update timeout 2251799813685371 --timeout 10000"),
	goldenFile: "testdata/update_job_timeout.golden",
},
```

There is a race condition safety build-in by waiting for some seconds between the setup commands (`setupCmds`) and the test command (`cmd`), which will await 3 seconds in this test case:

https://github.com/camunda/zeebe/blob/296f0391b934994241fd73fefb1832ee8c851dd7/clients/go/cmd/zbctl/main_test.go#L313-L318

But that was not enough. And it raises the question: why didn't the activate jobs fail? That is because the test is set up to run without long polling (if we had long polling enabled, there would be a better shot at having a job after activating although its not guaranteed):

https://github.com/camunda/zeebe/blob/296f0391b934994241fd73fefb1832ee8c851dd7/clients/go/cmd/zbctl/main_test.go#L251-L260

I expect this allows the `empty activate jobs` case to run fast by immediately returning `[]` rather than waiting for a long time.

https://github.com/camunda/zeebe/blob/296f0391b934994241fd73fefb1832ee8c851dd7/clients/go/cmd/zbctl/main_test.go#L162-L167

However, I run into issues with the `create worker` test case, which times out after 30 seconds, and I haven't figured out why yet.

---

While I'm unable to fully resolve that now, I can add a small remedy that could alleviate the pain a bit by spreading out the wait time between the commands. I'll open a PR for that.

**Comment by ana-vinogradova-camunda** [comment] 2024-01-04 08:52
@korthout thanks for such detailed investigation, it's very useful to know what happened there!

**Comment by berkaycanbc** [comment] 2024-05-29 12:58
Happened again:

CI logs: [link](https://github.com/camunda/camunda/actions/runs/9277444500/job/25526641981)
CI logs downloaded: [link](https://drive.google.com/drive/folders/11cCLQk82rsA58gLt1mn7HH34RYgZYStv)

@korthout as you mentioned since this is not fully resolved, I am re-opening the issue to discuss during the triage if there further possible improvements for this flakiness.

**Comment by remcowesterhoud** [comment] 2024-07-22 08:56
I've got a PR to add some more logging #20389. I struggle to reproduce it locally and this will at least provide more context if it fails again.
I'll close the issue in the PR so it'll get reopened when it occurs again.

**Closed** 2024-07-22 09:27 UTC
Labels: kind/flake, version:8.5.0-alpha1, version:8.1.23, version:8.3.6, version:8.2.21, version:8.4.1, version:8.5.0
