### ISSUE TITLE
OpenSearch retention policy

### ISSUE THREAD

**Issue by NingyuanZhang** [camunda/camunda#21707] opened 2024-08-28 23:18 UTC
**Describe the bug**

We have a running zeebe cluster with retention disabled, now we want to enable it. When i tested locally i found i couldn't enable it for a running zeebe, retention args only works when i create a new cluster. 
Looking at the code, it looks like you call updateRetentionPolicyForExistingIndices() method only when indexTemplate is not created, does that mean we cannot update or create retention for an existing cluster?
https://github.com/camunda/camunda/blob/main/zeebe/exporters/opensearch-exporter/src/main/java/io/camunda/zeebe/exporter/opensearch/OpensearchExporter.java#L91C1-L98C1 
@Override
  public void export(final Record<?> record) {
    if (!indexTemplatesCreated) {
      createIndexTemplates();
      updateRetentionPolicyForExistingIndices();
    }

**To Reproduce**

Create zeebe with retention policy disabled, then enable it, but the retention policy is not created or updated.

**Expected behavior**

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
<STACKTRACE>
```

</p>
</details>

**Environment:**
- OS: 
- Zeebe Version:  8.4.5
- Configuration: 
`services:
  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:${CAMUNDA_PLATFORM_VERSION:-8.4.4} 
    container_name: zeebe
    ports:
      - 26500:26500
      - 9600:9600
    environment: 
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_CLASSNAME=io.camunda.zeebe.exporter.opensearch.OpensearchExporter
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_URL=http://opensearch-node1:9200
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_AUTHENTICATION_USERNAME=admin
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_AUTHENTICATION_PASSWORD=admin
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_INDEX_CREATETEMPLATE=true
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_RETENTION_ENABLED=true
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_RETENTION_MINIMUMAGE=90d
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_RETENTION_POLICYNAME=testPolicy
      - ZEEBE_BROKER_EXPORTERS_OPENSEARCH_ARGS_RETENTION_POLICYDESCRIPTION=TEST
      ...
      `

**Comment by NingyuanZhang** [comment] 2024-08-29 23:37
one more question: currently opensearch exporter creates indices with date in the name, and every new index consumes one more more shards. is it possible to not have date in index name so that we only need to maintain one index? if not, do you have plan to implement this feature?
e.g. when opensearch exporter makes calls to "bulk" endpoint, it's doable to target index alias rather than index name:
POST _bulk?require_alias=true
{"index": { "_index": "sample-alias1", "_id": "4"} }
{ "age": "4" }

**Comment by koevskinikola** [comment] 2024-09-02 12:38
ZPA triage:
- The OS policy is applied in `8.4.6` (#17186). @NingyuanZhang can you check if the issue is resolved after upgrading your cluster to version `8.4.6`?
- @NingyuanZhang have you also restarted your cluster after applying the configuration changes?

**Comment by remcowesterhoud** [comment] 2024-09-02 13:57
@NingyuanZhang Please also note that the Policy is not created until a record is actually exported. Until this happens you won't see it.

**Comment by NingyuanZhang** [comment] 2024-09-04 14:01
ahh i think i tested changing the policy name but obviously it's not supported. 
Thank you! We are testing with different zeebe versions now.

**Comment by remcowesterhoud** [comment] 2024-09-04 14:27
@NingyuanZhang If you run into further problems when testing please let us know. For now I shall close this issue 🙂

**Closed by remcowesterhoud** 2024-09-04 14:27 UTC
Labels: kind/question, component/zeebe
