### ISSUE TITLE
8.4.0 tries to parse old process definition, leading to deployment error

### ISSUE THREAD

**Issue by Benjoyo** [camunda/camunda#15902] opened 2024-01-12 16:13 UTC
__Describe the Bug__

After upgrading our cluster to 8.4.0, we were unable to deploy one of our processes. 
We got an error like this:

```
Command 'CREATE' rejected with code 'PROCESSING_ERROR': Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=DEPLOYMENT, intent=CREATE, authorization=[...]}, value={"resources":[],"processesMetadata":[{"bpmnProcessId":"XYZ","version":101,"processDefinitionKey":2251799866782565,"resourceName":"diagram.bpmn","checksum":"ylETGz+fitu9RfpmrZ1F/w==","isDuplicate":false,"tenantId":"<default>"}],"decisionRequirementsMetadata":[],"decisionsMetadata":[],"formMetadata":[],"tenantId":"<default>"}}' without errors, but exception occurred with message 'Failed to build variable mapping expression: failed to parse expression '[...]'
```

The problem is not the error itself, but that the referenced expression is not part of the process for quite some time. We checked multiple times, downloaded the actual XML, checked and updated the connector templates etc. but it isn't there.
The engine seems to try to deploy a very old version of the process (or at least tries to parse it).

In fact, it is even impossible to deploy any newly created, completely empty .bpmn as long as it uses the same bpmnProcessId of the broken process definition and we get the same error referencing non-existent expressions. That is true for both web and desktop modeler. 

We could only resolve this by changing the process ID (and nothing else). But due to the fact that there is no way to delete old process definitions and it is impossible to overwrite it due to every deployment failing, we are now stuck with a process starting every morning at 9:00 and needed to rename the taskType of the first worker, so that it at least runs in an incident there :(
Therefore, I would consider this a pretty critical bug.

__Steps to Reproduce__

Unclear.

__Expected Behavior__

Newly deployed processes don't reference old definitions.

__Environment__
- Camunda version: 8.4.0 SaaS

**Comment by abbasadel** [comment] 2024-01-12 17:44
Hi @Benjoyo, thanks for the bug report. 

Since you are a SaaS customer, I would recommend reaching out to our [Support Channels](https://camunda.com/services/support/) where you can get priority assistance for your production issue.

**Comment by korthout** [comment] 2024-01-15 13:47
It's very likely that resolving #11253 resolves this issue as well. That issue is already prioritized, so let's await that outcome.

**Comment by saig0** [comment] 2024-01-23 08:09
Note that the deployment fails in version 8.4.0 because of regression when parsing the variable mappings ([ref](https://github.com/camunda/zeebe/issues/16043)).

**Comment by lenaschoenburg** [comment] 2024-07-26 07:23
@korthout looks like we can close this issue because @saig0 correctly diagnosed it as https://github.com/camunda/camunda/issues/16043 which is resolved now, right?

**Comment by korthout** [comment] 2024-07-26 14:09
Without looking to closely at the issue, you seem to be right. The error message in the original issue has the same cause as the referenced issue that has been resolved. This issue has also been stale for quite some time. Let's close this as completed. Please re-open if you still encounter this issue.

**Closed by korthout** 2024-07-26 14:09 UTC
Labels: kind/bug, component/zeebe
