### ISSUE TITLE
Built-in FEEL function `string(context)` produces incorrect results for instance variables

### ISSUE THREAD

**Issue by chillleader** [camunda/camunda#15209] opened 2023-11-15 09:56 UTC
**Describe the bug**

When trying to convert a FEEL context variable into a string using the built-in `string(any)` function, I observe incorrect output. 
A simple FEEL context object like `{"key1": {"key2": "value"}}` gets converted to:
`{key1:UnsafeBuffer{addressOffset=16, capacity=12, byteArray=byte[12], byteBuffer=null}}`

**To Reproduce**

I reproduced this issue with a connector but this should apply to all job workers.

1. Set up a job worker to test the issue:
   - It should consume a string variable called `myStringVar` from the process instance
   - It should log the input value to make the issue visible
3. Create a diagram to invoke this worker. Configure the following input mapping: `myStringVar = string(myContextVar)`.
4. Run an instance with the following context: `{"myContextVar": {"key1": {"key2": "value"}}}`
5. Verify that worker received the following value as an input: `{key1:UnsafeBuffer{addressOffset=16, capacity=12, byteArray=byte[12], byteBuffer=null}}`

**Expected behavior**

The following string is expected, as per FEEL Scala playground: `"{key1:{key2:\"value\"}}"`

**Log/Stacktrace**

N/A

**Environment:**
- OS: Camunda 8 SaaS 8.3.2
- Zeebe Version: 8.3.2
- Configuration: -

**Comment by berkaycanbc** [comment] 2023-11-29 14:52
ZPA Triage:

- The issue might the deserialising of the data received from FEEL Engine. Where Zeebe Engine has a bug while deserialising it.
- The issue might be resolved with newer versions of FEEL.
- We need investigate where the issue is exactly caused from.


@chillleader 
Was this working before, or it changed recently? **To assign a severity** to it, we would like to know if this is a regression or not?

**Comment by chillleader** [comment] 2023-11-29 17:22
Not sure if this was working before, as this was the first time I used `string(context)`.

I also tried to reproduce this in Connectors (that used FEEL-Scala 1.17.1 at the time) by evaluating the FEEL expression in a connector context and didn't face this issue.

**Comment by bastiankoerber** [comment] 2024-01-08 07:37
we have a another support request for this: https://github.com/camunda/zeebe/issues/15209
Can anyone name already an ETA?

**Comment by npepinpe** [comment] 2024-01-08 16:38
How urgent is this? Abbas is back on the 11th, so if it can wait until next week let's do that. Otherwise I can figure out something with the ZPA team.

**Comment by abbasadel** [comment] 2024-01-12 10:22
Related to support case: [SUPPORT-19836] (https://jira.camunda.com/browse/SUPPORT-19836)

**Comment by saig0** [comment] 2024-02-08 11:26
I created the following issue in the FEEL engine to fix the issue: https://github.com/camunda/feel-scala/issues/804

**Comment by mustafadagher** [comment] 2024-04-19 14:36
Opened a PR for the FEEL engine issue here https://github.com/camunda/feel-scala/pull/833

**Closed** 2024-08-22 06:13 UTC
Labels: kind/bug, severity/high, support, component/zeebe
