### ISSUE TITLE
ActorLifecyclePhasesAndTimersTest#shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase unstable

### ISSUE THREAD

**Issue by Zelldon** [camunda/camunda#19874] opened 2024-06-28 10:55 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail? once
- Does it block your work? Unclear, but it is not normal that this test fails!
- Do we suspect that it is a real failure? Yes

**Failures**
https://github.com/camunda/camunda/actions/runs/9711321464/job/26803827757
> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

<details><summary>Example assertion failure</summary>
<pre>
Warning:  Flakes: 
Warning:  io.camunda.zeebe.scheduler.lifecycle.ActorLifecyclePhasesAndTimersTest.shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase
Error:    Run 1: ActorLifecyclePhasesAndTimersTest.shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase:73 
Wanted but not invoked:
runnable.run();
-> at io.camunda.zeebe.scheduler.lifecycle.ActorLifecyclePhasesAndTimersTest.shouldExecuteTimersSubmittedInStartingPhaseWhenInStartedPhase(ActorLifecyclePhasesAndTimersTest.java:73)
Actually, there were zero interactions with this mock.
</pre>
</details>

**Hypotheses**

> List any hypotheses if you have one; can be ommitted

**Logs**

> If possible, provide more context here, e.g. standard output logs, link to build, etc.

[Test results for unit tests.zip](https://github.com/user-attachments/files/16028356/Test.results.for.unit.tests.zip)

**Comment by lenaschoenburg** [comment] 2024-07-25 09:55
I'm not able to reproduce this in >100k runs. I also don't have any idea how this test could fail, other than vague ones such as that task wakeup  or `ControlledActorSchedulerRule#workUntilDone` might not be 100% reliable.

**Comment by lenaschoenburg** [comment] 2024-09-12 09:19
I was reassigned but I still don't have any fresh ideas. Since I haven't seen this flake in a while, I'd close it until it happens again :disappointed:

**Closed by lenaschoenburg** 2024-09-12 09:19 UTC
Labels: kind/flake, component/zeebe
