### ISSUE TITLE
Flaky io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterElementCompleted

### ISSUE THREAD

**Issue by deepthidevaki** [camunda/camunda#18461] opened 2024-05-13 13:10 UTC
**Summary**

> Try to answer the following as best as possible

- How often does the test fail?
- Does it block your work?
- Do we suspect that it is a real failure?

**Failures**

> Outline known failure cases, e.g. a failed assertion and its stacktrace obtained from Jenkins

```
shouldCancelAfterJobComplete[parallel flow] (Flaky Test): io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest
java.util.concurrent.TimeoutException: Timeout after: 15 SECONDS
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:137)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:32)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:208)
	at io.camunda.zeebe.engine.util.TestStreams.buildStreamProcessor(TestStreams.java:275)
	at io.camunda.zeebe.engine.util.TestStreams.startStreamProcessor(TestStreams.java:218)
	at io.camunda.zeebe.engine.util.StreamProcessingComposite.startTypedStreamProcessor(StreamProcessingComposite.java:92)
	at io.camunda.zeebe.engine.util.StreamProcessorRule.startTypedStreamProcessor(StreamProcessorRule.java:141)
	at io.camunda.zeebe.engine.util.EngineRule.lambda$startProcessors$3(EngineRule.java:168)
	at io.camunda.zeebe.engine.util.EngineRule.forEachPartition(EngineRule.java:202)
	at io.camunda.zeebe.engine.util.EngineRule.startProcessors(EngineRule.java:163)
	at io.camunda.zeebe.engine.util.EngineRule.start(EngineRule.java:128)
	at io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.shouldCancelAfterJobComplete(CancelProcessInstanceConcurrentlyTest.java:176)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)

shouldCancelAfterElementCompleting[sub-process] (Flaky Test): io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest
java.util.concurrent.ExecutionException: Actor is closed
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:147)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.get(CompletableActorFuture.java:114)
	at io.camunda.zeebe.scheduler.FutureUtil.join(FutureUtil.java:21)
	at io.camunda.zeebe.scheduler.future.CompletableActorFuture.join(CompletableActorFuture.java:203)
	at io.camunda.zeebe.logstreams.util.SyncLogStream.newLogStreamWriter(SyncLogStream.java:77)
	at io.camunda.zeebe.engine.util.TestStreams$LogContext.newLogStreamWriter(TestStreams.java:430)
	at io.camunda.zeebe.engine.util.TestStreams.newLogStreamWriter(TestStreams.java:170)
	at io.camunda.zeebe.engine.util.TestStreams.newRecord(TestStreams.java:187)
	at io.camunda.zeebe.engine.util.StreamProcessingComposite.writeCommand(StreamProcessingComposite.java:154)
	at io.camunda.zeebe.engine.util.StreamProcessingComposite.writeCommand(StreamProcessingComposite.java:146)
	at io.camunda.zeebe.engine.util.StreamProcessorRule.writeCommand(StreamProcessorRule.java:195)
	at io.camunda.zeebe.engine.util.client.DeploymentClient.deploy(DeploymentClient.java:174)
	at io.camunda.zeebe.engine.processing.processinstance.CancelProcessInstanceConcurrentlyTest.init(CancelProcessInstanceConcurrentlyTest.java:131)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
Caused by: java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamWriter(LogStreamImpl.java:156)
	... 10 more

```

**Hypotheses**

**Logs**
https://github.com/camunda/zeebe/actions/runs/9063172403

[Test results for unit tests.zip](https://github.com/camunda/zeebe/files/15294949/Test.results.for.unit.tests.zip)

**Comment by mustafadagher** [comment] 2024-05-29 12:06
I couldn't reproduce this locally, but inspecting the logs from the test results, below is a complete stacktrace of the errors:

It seems from the logs that the actor was closed and it was failing to start again. I see also several `NullPointerException`s for `logStreamReader` and `asyncActor ` being null.

I'm not sure, but I feel like someone from @camunda/zeebe-distributed-platform should have a look at this too.

<details><summary>Logs</summary>
<pre>
12:54:28.213 [LogStream-1] ERROR io.camunda.zeebe.logstreams - Unexpected error in Log Stream LogStream-1 in phase STARTED.
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@45a75521[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@35e5cd8e[Wrapped task = io.camunda.zeebe.engine.util.ProcessingExporterTransistor$$Lambda/0x00007cecf0718800@6753ae3f]] rejected from java.util.concurrent.ThreadPoolExecutor@2b9cc193[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 5]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1371) ~[?:?]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:785) ~[?:?]
	at io.camunda.zeebe.engine.util.ProcessingExporterTransistor.onNewEventCommitted(ProcessingExporterTransistor.java:66) ~[test-classes/:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.notifyRecordAwaiters(LogStreamImpl.java:184) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.lambda$call$0(ActorControl.java:75) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:88) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
12:54:28.231 [LogStream-1] INFO  io.camunda.zeebe.logstreams - On closing logstream stream-1 close 16 readers
12:54:28.299 [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Unexpected error on retrieving reader from log stream.
java.lang.RuntimeException: Actor is closed
	at io.camunda.zeebe.scheduler.ActorJob.failFuture(ActorJob.java:172) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:84) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ClosedQueue.offer(ClosedQueue.java:15) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.submit(ActorTask.java:102) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorControl.call(ActorControl.java:172) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.logstreams.impl.log.LogStreamImpl.newLogStreamReader(LogStreamImpl.java:149) ~[zeebe-logstreams-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.StreamProcessor.onActorStarting(StreamProcessor.java:155) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
12:54:28.307 [StreamProcessor-1] DEBUG io.camunda.zeebe.logstreams - Recovering state of partition 1 from snapshot
12:54:28.307 [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED.
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.logstreams.log.LogStreamReader.seekToNextEvent(long)" because "this.logStreamReader" is null
	at io.camunda.zeebe.stream.impl.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:402) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.StreamProcessor.onActorStarted(StreamProcessor.java:163) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
12:54:28.307 [StreamProcessor-1] ERROR io.camunda.zeebe.logstreams - Actor StreamProcessor-1 failed in phase STARTED.
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.stream.impl.StreamProcessor$AsyncProcessingScheduleServiceActor.closeAsync()" because "this.asyncActor" is null
	at io.camunda.zeebe.stream.impl.StreamProcessor.onFailure(StreamProcessor.java:428) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.StreamProcessor.onActorStarted(StreamProcessor.java:228) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
12:54:28.310 [StreamProcessor-1] ERROR io.camunda.zeebe.util.actor - Unexpected error occurred in task StreamProcessor-1 ACTIVE phase: STARTED
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.stream.impl.StreamProcessor$AsyncProcessingScheduleServiceActor.closeAsync()" because "this.asyncActor" is null
	at io.camunda.zeebe.stream.impl.StreamProcessor.onFailure(StreamProcessor.java:428) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.stream.impl.StreamProcessor.handleFailure(StreamProcessor.java:261) ~[zeebe-stream-platform-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.onFailure(ActorTask.java:301) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:56) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) ~[zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-SNAPSHOT.jar:8.6.0-SNAPSHOT]
</pre>
</details>

**Comment by mustafadagher** [comment] 2024-08-01 10:46
Can we assume this might have been fixed with https://github.com/camunda/camunda/pull/20339?

**Comment by lenaschoenburg** [comment] 2024-08-01 10:50
Yes, at least this specific case looks to be solved :+1:

**Closed by lenaschoenburg** 2024-08-01 10:50 UTC
Labels: kind/flake, component/zeebe
