### ISSUE TITLE
Flaky PartitionTransitionImplTest.shouldAbortOngoingTransitionWhenNewTransitionIsRequested

### ISSUE THREAD

**Issue by npepinpe** [camunda/camunda#18445] opened 2024-05-13 06:47 UTC
**Summary**

- How often does the test fail?
  - Twice
- Does it block your work?
  - No
- Do we suspect that it is a real failure?
  - Likely not

**Failures**

<details><summary>Example assertion failure</summary>
<pre>
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.remove(ArrayList.java:551)
	at io.camunda.zeebe.broker.system.partitions.impl.PartitionTransitionProcess.lambda$proceedWithTransition$1(PartitionTransitionProcess.java:88)
	at io.camunda.zeebe.scheduler.testing.TestConcurrencyControl.run(TestConcurrencyControl.java:50)
</pre>
</details>

**Comment by oleschoenburg** [comment] 2024-05-21 08:23
I couldn't reproduce this yet. The exception says that `PartitionTransitionProcess` tries to remove from `pendingSteps` but it's empty. As far as I can tell, this can only happen if `PartitionTransitionProcess` isn't thread safe. Since the test uses `TestConcurrencyControl` which behaves differently to the production version, I suspect a concurrency issue that is test-only and difficult to trigger.

**Comment by lenaschoenburg** [comment] 2024-06-18 08:13
I couldn't reproduce this in 14k runs! Running all tests in `PartitionTransitionImplTest` also can't reproduce the problem.
I haven't seen this fail lately so I'd close this until it occurs again. If it does, please note the commit where it failed.

**Comment by tmetzke** [comment] 2024-07-05 07:06
Failed again: https://github.com/camunda/camunda/actions/runs/9804076951/job/27071247630

[Test results.zip](https://github.com/user-attachments/files/16106192/Test.results.zip)

**Closed** 2024-07-19 08:37 UTC
Labels: kind/flake, component/zeebe
