### ISSUE TITLE
Process modification on inclusive gateway makes active token disappear

### ISSUE THREAD

**Issue by alan-pilic-ca** [camunda/camunda#25099] opened 2024-11-22 21:58 UTC
**Describe the bug**

Process modification on inclusive gateway makes active token disappear

**To Reproduce**

1. Navigate to process instance in Operate UI
2. Select modify instance wrench
3. On current activity, select move instance
4. Select the inclusive gateway
5. Apply modifications
6. No active token appears but the process continues

**Expected behavior**

Active token appears on current process or user is not allowed to make this action.

**Environment:**
C8 SaaS 8.6

JIRA ticket for reference:

https://jira.camunda.com/browse/SUPPORT-24445

**Comment by lzgabel** [comment] 2024-11-23 05:56
similar to #20587

**Comment by korthout** [comment] 2024-11-26 09:35
@alan-pilic-ca Do you see this as a duplicate of #20587

**Comment by tmetzke** [comment] 2024-11-27 07:20
I believe this issue was meant to express something else regarding the support case it's related to:
* We must prevent users from executing this operation as long as #20587 hasn't been tackled.
* We should document that this doesn't work with an inclusive gateway.

**Comment by korthout** [comment] 2024-12-09 14:40
[My latest finding](https://github.com/camunda/camunda/issues/20587#issuecomment-2528129487) is that it should be simple to resolve 
- https://github.com/camunda/camunda/issues/20587

I'm in favor of taking that approach over preventing activation of inclusive gateway in modification.

**Closed** 2024-12-09 19:00 UTC
Labels: kind/bug, severity/mid, support, likelihood/high, component/zeebe
