### ISSUE TITLE
Event replay fails during cluster update due to unknown applier version

### ISSUE THREAD

**Issue by koevskinikola** [camunda/camunda#23769] opened 2024-10-21 13:48 UTC
**Describe the bug**

During an update from `8.5.8` to `8.6.0` an `8.5.8` Zeebe broker was restarted an started replaying events. Eventually, it replayed a `Process.CREATED#v2` event which was added/created in Zeebe `8.6.0` and an exception was thrown. 

The error led to the stream processor to fail.

**To Reproduce**

I wasn't able to reproduce the issue, but I could see that an upgrade triggered it [here](https://accounts.cloud.camunda.io/organizations/198d7494-da34-42b1-ad8a-8e6d107a20f9/clusters/686ae105-3a4c-4493-a673-3b90da29b9ca) (internal link). 

**Expected behavior**

Events with unknown, i.e. newer versions are handled gracefully during Zeebe upgrades.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.RuntimeException: Failed to replay batch at 'LoggedEvent [position=4349786, key=2251799815859321, timestamp=1729283168696, sourceEventPosition=4349785] RecordMetadata{recordType=EVENT, valueType=PROCESS, intent=CREATED, authorization=UNKNOWN}'
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$4(ReplayStateMachine.java:170) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.future.FutureContinuationRunnable.run(FutureContinuationRunnable.java:33) ~[zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:96) ~[zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.5.8.jar:8.5.8]
Caused by: io.camunda.zeebe.engine.state.EventApplier$NoSuchEventApplier$NoApplierForVersion: Expected to find an event applier for intent 'CREATED' and version '2', but '1' is the latest supported version.
	at io.camunda.zeebe.engine.state.appliers.EventAppliers.applyState(EventAppliers.java:437) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.engine.Engine.replay(Engine.java:95) ~[zeebe-workflow-engine-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.replayEvent(ReplayStateMachine.java:237) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$tryToReplayBatch$5(ReplayStateMachine.java:210) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.tryToReplayBatch(ReplayStateMachine.java:208) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.stream.impl.ReplayStateMachine.lambda$replayNextEvent$3(ReplayStateMachine.java:164) ~[zeebe-stream-platform-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.retry.ActorRetryMechanism.run(ActorRetryMechanism.java:28) ~[zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.retry.RecoverableRetryStrategy.run(RecoverableRetryStrategy.java:48) ~[zeebe-scheduler-8.5.8.jar:8.5.8]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) ~[zeebe-scheduler-8.5.8.jar:8.5.8]
	... 5 more

```

</p>
</details>

**Environment:**
- OS: Camunda SaaS
- Zeebe Version: `8.5.8` (during upgrade to `8.6.0`)
- Configuration: 
- [GCP logs (internal)
](https://console.cloud.google.com/logs/query;query=logName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.container_name%3D%22zeebe%22%0Aresource.labels.pod_name%3D%22zeebe-0%22%0Aresource.labels.namespace_name%3D%22686ae105-3a4c-4493-a673-3b90da29b9ca-zeebe%22%0Aresource.labels.location%3D%22europe-west1%22%0Aresource.labels.cluster_name%3D%22production-worker-1%22%0Aresource.labels.project_id%3D%22camunda-cloud-240911%22;pinnedLogId=2024-10-18T20:26:09.833211381Z%2Fa3sxb2pbcy5udmr1;cursorTimestamp=2024-10-18T20:26:09.833972419Z;startTime=2024-10-18T19:56:39.833Z;endTime=2024-10-18T20:56:39.833Z?project=camunda-cloud-240911)
- [GCP logs](https://drive.google.com/file/d/1jmTjTdiz2YKvAgdhrbF8xXrcNLRyAAos/view?usp=sharing) (downloaded; internal)

**Comment by koevskinikola** [comment] 2024-10-21 13:50
Individual triage:
- Severity and impact are `low`, as the (older version) node can't process this event in any case, the node will eventually be upgraded to a newer Zeebe version which can process this event.

**Comment by lenaschoenburg** [comment] 2024-10-21 13:53
Not a bug but intended behavior as far as I can tell. It's logged as ERROR because it's only expected shortly, during a rolling update. Outside of that, it's an unexpected error so I wouldn't change the log level either.

**Comment by korthout** [comment] 2024-10-28 13:32
>Not a bug but intended behavior as far as I can tel

I agree. There's no way for this broker to replay the event correctly, so it needs to stop replaying.

> It's logged as ERROR because it's only expected shortly, during a rolling update. Outside of that, it's an unexpected error so I wouldn't change the log level either.

Agreed. Additionally, the log level could be WARN rather than ERROR under the condition that there is a rolling update happening. 

@lenaschoenburg Is there a way for a broker to know that a rolling update is going on? This would help us avoid unnecessary noise from Google Error Reporting.

**Comment by lenaschoenburg** [comment] 2024-10-28 13:40
> @lenaschoenburg Is there a way for a broker to know that a rolling update is going on? This would help us avoid unnecessary noise from Google Error Reporting.

Not a reliable one as far as I remember. I'd accept it as noise for now.

**Comment by koevskinikola** [comment] 2024-10-28 14:08
In that case, I'm closing this issue.

**Comment by rodrigo-lourenco-lopes** [comment] 2024-11-22 13:07
We have this issue happening in more places: 

https://console.cloud.google.com/errors/detail/CLmJrZGJ1rWTdw;service=zeebe;time=P7D;locations=global?inv=1&invt=AbiKsA&project=camunda-cloud-240911

This particular case was updating from "Camunda 8.5+gen12" to "Camunda 8.6+gen4".
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/5e77d880-c2fa-490c-8bb2-0ed072a420e4">

**Comment by lenaschoenburg** [comment] 2024-11-22 13:11
@rodrigo-lourenco-lopes Has anything changed in regards to impact? Closing it was a deliberate choice: https://github.com/camunda/camunda/issues/23769#issuecomment-2441602884

**Comment by rodrigo-lourenco-lopes** [comment] 2024-11-22 13:57
> @rodrigo-lourenco-lopes Has anything changed in regards to impact? Closing it was a deliberate choice: [#23769 (comment)](https://github.com/camunda/camunda/issues/23769#issuecomment-2441602884)

Ups I did not mean to reopen, just to add a comment 😬

**Closed by rodrigo-lourenco-lopes** 2024-11-22 13:57 UTC
Labels: kind/bug, severity/low, impact/low, component/zeebe
