### ISSUE TITLE
`mvn -PcheckFormat spotless:check` and `mvn spotless:check` behave differently

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda#21191] opened 2024-08-15 14:48 UTC
## Introduction

`mvn -PcheckFormat spotless:check` and `mvn spotless:check` behave differently

## How to reproduce

When a CI check fails due to a malformed `.md` file, the CI suggest to run `mvn spotless:apply` to fix the issue. However, it seems that `mvn -PcheckFormat spotless:check` and `mvn spotless:check` behave differently.

Example: 
1. See failed CI run https://github.com/camunda/camunda/commit/91a433c1ed04534fed15471debe1641b4507b61e
2. See suggestion to run `mvn spotless:apply`

## Expected behavior

CI suggestion how to resolve a formatting issue (here: `spotless:apply`) works. (Alternative: CI should suggest to run `mvn -PcheckFormat spotless:check` in the first place

## Additional context:

See [thread](https://camunda.slack.com/archives/C013MEVQ4M9/p1723720691100259)

**Comment by korthout** [comment] 2024-08-15 17:23
**What is the difference between the `autoFormat` and `checkFormat` maven profiles?**
One difference between the `autoFormat` profile (which is enabled if no other profile is enabled) and the `checkFormat` profile is the `ratchetFrom: main` configuration:

https://github.com/camunda/camunda/blob/d7f9b87f79454b43beb59eb2b685f40224336552/bom/pom.xml#L283-L295

**What is ratcheting?**
[Ratcheting](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#how-can-i-enforce-formatting-gradually-aka-ratchet) is a spotless feature to allow gradual alignment to formatting by only comparing (checking or applying) files that are different to those referenced by the git ref `origin/main`. In other words, it only processes those files with (local) changes compared to main.

Ratcheting from `origin/main` is only enabled when `autoFormat` is enabled. And `autoFormat` is enabled by default when you just run `mvn spotless:apply` or `mvn spotless:check` because no other profile is specified.

**What can we conclude?**
We can state that:
- the CI `Java Checks` job compares all code (but [only runs when specific files are changed](https://github.com/camunda/camunda/blob/96c3612ab36e76b8832ca3f916d9cc957fd23c65/.github/actions/paths-filter/action.yml#L14-L23))
- `mvn spotless:apply` and `mvn spotless:check` only process files changed in comparison to `origin/main`
- `mvn spotless:apply` and `mvn spotless:check` actually do work correctly as long as we don't have invalid formatting on main
- with #21172 merged, we should not have invalid formatting on main

I confirmed this by disabling `ratchetFrom` altogether and noticed that:
- `origin/main` is completely formatted correctly already
- `mvn spotless:check` and `mvn spotless:apply` run much faster without `ratchetFrom`
  - 12s without vs 48s with `ratchetFrom` (using [`mvnd`](https://github.com/apache/maven-mvnd) without [spotless index files](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md#incremental-up-to-date-checking-and-formatting))
  - possibly it became slow because our repo has grown so much since we introduced spotless

**Proposal**
IMO, we have no need for `ratchetFrom` anymore (all code is already formatted accordingly), and can remove it to:
- resolve this issue
- speed up all spotless runs

**Closed** 2024-08-16 12:41 UTC
Labels: area/project, area/build, component/build-pipeline
