### ISSUE TITLE
Implementation of  Usage metrics with distinct count in Elasticsearch and OpenSearch

### ISSUE THREAD

**Issue by ralfpuchert** [camunda/camunda#26105] opened 2024-12-16 09:06 UTC
### Description

Follow up of https://github.com/camunda/camunda/pull/25690

The Usage metrics are implemented as distinct count via Java Stream API.
For a higher amount of metric entries in the indices it won't scale.

For Elasticsearch and OpenSearch implementation aggregations are needed.
In v1 [implementation](https://github.com/camunda/camunda/blob/b6a26fb9e20a68df32f28b2c4d9832f4ba982536/operate/schema/src/main/java/io/camunda/operate/store/elasticsearch/dao/Query.java#L50) [TermsAggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html) are used.

Aggregations need to be added in SearchRequest and SearchResponse

### Acceptance Criteria 

- [ ] Implement distinct count on assignees for tasklist metric index
- [ ] Implement distinct count on process instances for operate metric index
- [ ] Implement distinct count on decision instances for operate metric index

Note: For process instances and decision instances it should be sufficient to count only by event.
There should't be duplicates for process instance keys or decision instance keys.
For Tasklist assignees can be assigned to more than one task. Here is a distinct necessary.

```[tasklist]
### Pull Requests
```

**Comment by tmetzke** [comment] 2024-12-16 12:33
Duplicate of #26106

**Closed by tmetzke** 2024-12-16 12:33 UTC
Labels: kind/task, component/c8-api
