### ISSUE TITLE
Process instance banned for timer trigger command with unknown process

### ISSUE THREAD

**Issue by korthout** [camunda/camunda#20677] opened 2024-07-31 15:51 UTC
**Describe the bug**

An error was reported for a banned instance due to an error:
>Expected to process record 'TypedRecordImpl{metadata=RecordMetadata{recordType=COMMAND, valueType=TIMER, intent=TRIGGER, authorization=UNKNOWN}, value={"elementInstanceKey":-1,"processInstanceKey":6755399442538720,"dueDate":1722334004219,"targetElementId":"<REDACTED>","repetitions":2,"processDefinitionKey":2251799815154549,"tenantId":"<default>"}}' without errors, but exception occurred with message 'Expected to find a process deployed with key '2251799815154549' but not found.'.

**To Reproduce**

I haven't researched this yet, but it seems that the process has been deleted before the timer triggered. We could look into cases with timers for process instances and deleting their process definition.

**Expected behavior**

A trigger timer command shouldn't lead to a banned instance.

**Log/Stacktrace**

<details><summary>Full Stacktrace</summary>
 <p>

```
java.lang.IllegalStateException: Expected to find a process deployed with key '2251799815154549' but not found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:364) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.engine.processing.timer.TimerTriggerProcessor.processRecord(TimerTriggerProcessor.java:93) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:371) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:242) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
java.lang.IllegalStateException: Expected to find a process deployed with key '2251799815154549' but not found.
	at io.camunda.zeebe.engine.state.deployment.DbProcessState.getFlowElement(DbProcessState.java:364) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.engine.processing.timer.TimerTriggerProcessor.processRecord(TimerTriggerProcessor.java:93) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.engine.Engine.process(Engine.java:127) ~[zeebe-workflow-engine-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.batchProcessing(ProcessingStateMachine.java:371) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.lambda$processCommand$3(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.db.impl.rocksdb.transaction.ZeebeTransaction.run(ZeebeTransaction.java:116) ~[zeebe-db-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.processCommand(ProcessingStateMachine.java:284) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.stream.impl.ProcessingStateMachine.tryToReadNextRecord(ProcessingStateMachine.java:242) ~[zeebe-stream-platform-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.invoke(ActorJob.java:94) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorJob.execute(ActorJob.java:47) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorTask.execute(ActorTask.java:122) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.executeCurrentTask(ActorThread.java:130) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.doWork(ActorThread.java:108) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
	at io.camunda.zeebe.scheduler.ActorThread.run(ActorThread.java:227) [zeebe-scheduler-8.6.0-alpha2.jar:8.6.0-alpha2]
```

</p>
</details>

**Environment:**
- Zeebe Version: `8.6.0-alpha2`
- Logs: [link](https://cloudlogging.app.goo.gl/BysUVshWgLCtkXGfA)
- Logs: [Drive](https://drive.google.com/drive/folders/1iXiI_TlHqMQkDwhgTOW07SowYi1CzbEA)
- Error: [Google](https://console.cloud.google.com/errors/detail/CMiX0tT5vr-WXg;service=zeebe;time=P7D;locations=global?project=camunda-cloud-240911)

**Comment by korthout** [comment] 2024-07-31 15:59
Marking this as critical, as a banned instance could be considered loss of data.

**Comment by korthout** [comment] 2024-07-31 16:09
There are logs indicating that there was a resource deletion right before the error occurred:

<details><summary>2024-07-30 12:02:30.69: 2 RESOURCE_DELETION</summary>
<p>

```
Current exporter state {elasticsearch={position=2968953, metadata={"recordCountersByValueType":{"JOB":126,"DEPLOYMENT":165,"PROCESS_INSTANCE":2486,"INCIDENT":30,"TIMER":26,"VARIABLE":883,"PROCESS_INSTANCE_CREATION":41,"PROCESS":71,"RESOURCE_DELETION":2,"COMMAND_DISTRIBUTION":996}}}, MetricsExporter={position=2968953, metadata=}}
  {
    "insertId": "9a6kggpdxdtedbm4",
    "jsonPayload": {
      "context": {
        "threadPriority": 5,
        "actor-name": "Exporter-1",
        "loggerName": "io.camunda.zeebe.broker.exporter",
        "actor-scheduler": "Broker-2",
        "threadName": "zb-fs-workers-0",
        "threadId": 21,
        "partitionId": "1"
      },
      "serviceContext": {
        "service": "zeebe",
        "version": "8.6.0-alpha2"
      },
      "message": "Current exporter state {elasticsearch={position=2968953, metadata={\"recordCountersByValueType\":{\"JOB\":126,\"DEPLOYMENT\":165,\"PROCESS_INSTANCE\":2486,\"INCIDENT\":30,\"TIMER\":26,\"VARIABLE\":883,\"PROCESS_INSTANCE_CREATION\":41,\"PROCESS\":71,\"RESOURCE_DELETION\":2,\"COMMAND_DISTRIBUTION\":996}}}, MetricsExporter={position=2968953, metadata=}}"
    },
    "resource": {
      "type": "k8s_container",
      "labels": {
        "namespace_name": "cf8c2c0c-6a52-4985-a0d5-56026811a141-zeebe",
        "pod_name": "zeebe-2",
        "location": "europe-west1",
        "project_id": "camunda-cloud-240911",
        "cluster_name": "production-worker-1",
        "container_name": "zeebe"
      }
    },
    "timestamp": "2024-07-30T10:02:30.696552352Z",
    "severity": "DEBUG",
    "labels": {
      "k8s-pod/statefulset_kubernetes_io/pod-name": "zeebe-2",
      "k8s-pod/cloud_camunda_io/salesPlanType": "trial",
      "k8s-pod/cloud_camunda_io/clusterPlanType": "Trial_Cluster",
      "k8s-pod/app_kubernetes_io/app": "zeebe",
      "compute.googleapis.com/resource_name": "gke-production-worker-1-spot-v3-7e4d8f49-djsh",
      "k8s-pod/cloud_camunda_io/channel": "Alpha",
      "k8s-pod/controller-revision-hash": "zeebe-7885876d75",
      "k8s-pod/cloud_camunda_io/generation": "Camunda_8_6_0_alpha2",
      "k8s-pod/cloud_camunda_io/orgId": "2c364f6d_1294_48c6_ad44_ee4c33107111",
      "k8s-pod/cloud_camunda_io/internalSalesPlan": "false",
      "k8s-pod/app_kubernetes_io/component": "gateway",
      "k8s-pod/cloud_camunda_io/clusterPlan": "G3_Trial",
      "k8s-pod/cloud_camunda_io/salesPlan": "Trial_with_Low_Hardware"
    },
    "logName": "projects/camunda-cloud-240911/logs/stdout",
    "sourceLocation": {
      "file": "ThrottledLogger.java",
      "line": "116",
      "function": "lambda$debug$11"
    },
    "receiveTimestamp": "2024-07-30T10:02:33.942559178Z"
  }
```

</p>
</details> 

<details><summary>2024-07-30 12:03:31.632: 4 RESOURCE_DELETION</summary>
<p>

```
Current exporter state {elasticsearch={position=2969648, metadata={"recordCountersByValueType":{"JOB":126,"DEPLOYMENT":166,"PROCESS_INSTANCE":2486,"INCIDENT":30,"TIMER":26,"VARIABLE":883,"PROCESS_INSTANCE_CREATION":41,"PROCESS":73,"RESOURCE_DELETION":4,"COMMAND_DISTRIBUTION":1008}}}, MetricsExporter={position=2969648, metadata=}}
  {
    "insertId": "hg1wk8su9hz33fun",
    "jsonPayload": {
      "context": {
        "actor-name": "Exporter-1",
        "threadName": "zb-fs-workers-0",
        "actor-scheduler": "Broker-2",
        "partitionId": "1",
        "loggerName": "io.camunda.zeebe.broker.exporter",
        "threadPriority": 5,
        "threadId": 21
      },
      "message": "Current exporter state {elasticsearch={position=2969648, metadata={\"recordCountersByValueType\":{\"JOB\":126,\"DEPLOYMENT\":166,\"PROCESS_INSTANCE\":2486,\"INCIDENT\":30,\"TIMER\":26,\"VARIABLE\":883,\"PROCESS_INSTANCE_CREATION\":41,\"PROCESS\":73,\"RESOURCE_DELETION\":4,\"COMMAND_DISTRIBUTION\":1008}}}, MetricsExporter={position=2969648, metadata=}}",
      "serviceContext": {
        "service": "zeebe",
        "version": "8.6.0-alpha2"
      }
    },
    "resource": {
      "type": "k8s_container",
      "labels": {
        "cluster_name": "production-worker-1",
        "container_name": "zeebe",
        "namespace_name": "cf8c2c0c-6a52-4985-a0d5-56026811a141-zeebe",
        "location": "europe-west1",
        "project_id": "camunda-cloud-240911",
        "pod_name": "zeebe-2"
      }
    },
    "timestamp": "2024-07-30T10:03:31.632701201Z",
    "severity": "DEBUG",
    "labels": {
      "k8s-pod/cloud_camunda_io/orgId": "2c364f6d_1294_48c6_ad44_ee4c33107111",
      "k8s-pod/cloud_camunda_io/salesPlanType": "trial",
      "k8s-pod/app_kubernetes_io/component": "gateway",
      "k8s-pod/cloud_camunda_io/internalSalesPlan": "false",
      "k8s-pod/cloud_camunda_io/clusterPlan": "G3_Trial",
      "k8s-pod/cloud_camunda_io/salesPlan": "Trial_with_Low_Hardware",
      "k8s-pod/app_kubernetes_io/app": "zeebe",
      "k8s-pod/cloud_camunda_io/clusterPlanType": "Trial_Cluster",
      "k8s-pod/statefulset_kubernetes_io/pod-name": "zeebe-2",
      "compute.googleapis.com/resource_name": "gke-production-worker-1-spot-v3-7e4d8f49-djsh",
      "k8s-pod/cloud_camunda_io/channel": "Alpha",
      "k8s-pod/controller-revision-hash": "zeebe-7885876d75",
      "k8s-pod/cloud_camunda_io/generation": "Camunda_8_6_0_alpha2"
    },
    "logName": "projects/camunda-cloud-240911/logs/stdout",
    "sourceLocation": {
      "file": "ThrottledLogger.java",
      "line": "116",
      "function": "lambda$debug$11"
    },
    "receiveTimestamp": "2024-07-30T10:03:33.918484825Z"
  }
```

</p>
</details> 

Error occurs at `2024-07-30 12:06:44.363`

**Comment by korthout** [comment] 2024-07-31 16:10
There are logs indicating that there was a resource deletion right before the error occurred:

<details><summary>2024-07-30 12:02:30.69: 2 RESOURCE_DELETION</summary>
<p>

```
Current exporter state {elasticsearch={position=2968953, metadata={"recordCountersByValueType":{"JOB":126,"DEPLOYMENT":165,"PROCESS_INSTANCE":2486,"INCIDENT":30,"TIMER":26,"VARIABLE":883,"PROCESS_INSTANCE_CREATION":41,"PROCESS":71,"RESOURCE_DELETION":2,"COMMAND_DISTRIBUTION":996}}}
```

</p>
</details> 

<details><summary>2024-07-30 12:03:31.632: 4 RESOURCE_DELETION</summary>
<p>

```
Current exporter state {elasticsearch={position=2969648, metadata={"recordCountersByValueType":{"JOB":126,"DEPLOYMENT":166,"PROCESS_INSTANCE":2486,"INCIDENT":30,"TIMER":26,"VARIABLE":883,"PROCESS_INSTANCE_CREATION":41,"PROCESS":73,"RESOURCE_DELETION":4,"COMMAND_DISTRIBUTION":1008}}
```

</p>
</details> 

Error occurs at `2024-07-30 12:06:44.363`

**Comment by korthout** [comment] 2024-07-31 16:16
We can only delete processes if they have no active (running) process instances. However, banned process instances are not considered active.

https://github.com/camunda/camunda/blob/fe6435a4a1359d7c9b73d14b9e743b9232bca783/zeebe/engine/src/main/java/io/camunda/zeebe/engine/state/instance/DbElementInstanceState.java#L406-L407

However, a banned process instance may still have timers triggering for it:
- https://github.com/camunda/camunda/issues/14213

**Comment by megglos** [comment] 2024-08-01 07:38
@korthout one thought, I understand that in this the banning was triggered due to the process being deleted, so the cause is related to a process delete operation where we expect no instance to be running anymore anyway. So the outcome of getting instances banned related to a deleted process actually appears not critical too me as this is effectively no data loss (as the instance should not exist anymore at that point anyway). If I didn't miss anything I would classify this as high severity still but not critical as the user is likely not caring about instances anymore of a process they deleted.

What do you think of this?

**Comment by korthout** [comment] 2024-08-01 08:03
@megglos No, this process instance was not banned yet. See my edit in [this comment](https://github.com/camunda/camunda/issues/20677#issuecomment-2260891748).

So, somehow we have a timer trigger for a process instance that wasn't banned and for which the process definition is deleted. 

Some options:
1. Perhaps the process instance has been completed/terminated and the timer instance was not properly cleaned up.
2. Perhaps the process instance was still active even though the process definition has already been deleted

Case 2 is loss of data. We need to investigate that the process instance was truly inactive at the time of the resource deletion.

💭 One thing that comes to mind is that the process instance `6755399442538720` was created on partition `3` (note the key's prefix `67*`). Perhaps this is something to command distribution in combination with resource deletion. Still, I want to first understand what the state of this process instance was.

**Comment by megglos** [comment] 2024-08-01 10:23
> Case 2 is loss of data.

@korthout and me aligned on this, we concluded to evaluate it as high but not critical, because:

- The user triggering a defition deletion from Operate(which we assume to be the majority) is informed about the termination of instanced related to that definition https://docs.camunda.io/docs/components/operate/userguide/delete-resources/#delete-process-definition-from-processes-page => the expected outcome of a successful deletion is, no process instance is present anymore after => thus the current situation is not a data loss from a users perspective who was expecting to stop all their processes related to it
- And instance being present after a successful deletion is unexpected and an inconsistency that needs investigation, however given that the lack of the definition prevents that instance from progressing in any way it doesn't cause harm either

We have the assumption this may be a race condition between a cancel instance batch operation done by operate as part of deleting a definition, see step 4 on https://docs.camunda.io/docs/components/operate/userguide/delete-resources/#delete-process-definition-from-processes-page combined with the fact that on resource deletion we can only check for the presence of an instance on partition 1, while there could be instances started after Operate started a cancellation batch on a different partition

**Comment by korthout** [comment] 2024-08-01 10:45
> the fact that on resource deletion we can only check for the presence of an instance on partition 1

That's not really how I meant it. On other partitions we also have this check. It is part of the `tryDeleteResources()` method. 

https://github.com/camunda/camunda/blob/90f4283fbc4a3d93b11a736ae9633cf06abd2e92/zeebe/engine/src/main/java/io/camunda/zeebe/engine/processing/resource/ResourceDeletionDeleteProcessor.java#L115-L118

If there are process instances, an exception is thrown which rollsback the transaction and ensures no records are actually appended, followed by a rejection of the command. As the distributed command is not acknowledged, the distributing partition will continue to retry sending the delete command until the resource is successfully deleted on this partition as well.

**Comment by megglos** [comment] 2024-08-01 10:54
so the distributed delete command should have never gotten acknowledged on a partition in case there was a running instance still

**Comment by megglos** [comment] 2024-08-01 11:16
So in Operate you are required to cancel instances before you are allowed to delete the process.
You can do that with a batch operation selecting all instances.

However I could start the delete, concurrently starting a new instance and the delete still succeeds in Operate. The instance is still listed but the process is gone from Operate. (But likely still present in Zeebe?) Will validate and follow-up with Operate (out of scope here)

**Comment by tmetzke** [comment] 2024-08-01 12:00
# Plan of action (work in progress, will be updated)

## How is a process definition deleted on multiple partitions?

1. Deletion request on partition 1
   1. Lookup of active instances on partition 1
   2. No active instances found -> delete resource on partition 1
2. Successful response to resource deletion
3. Distribution of deletion to other partitions
4. Partition 2 processes the distributed delete
   1. Lookup of active instances on partition 2
   2. No active instances found -> delete resource on partition 2
   3. Acknowledge the distributed delete command to partition 1
5. Partition 3 processes the distributed delete
   1. Lookup of active instances on partition 3
   2. Active instances found -> deletion rejected
   3. Reject the distributed delete command to partition 1
6. Retry delete command distribution again later until successfull
  (might be an endless loop until the active instances on partition 3 have been canceled)

## How is the timer correlated to the process instance and definition?

* The timer is due and triggered.
* The process instance is looked up on partition 3 (identifiable based on the job key stored in the timer)
* The process definition is looked up on partition 3 (same as the process instance)

## Possible cases

- The process instance gone as well on partition 3 --> Why was the timer not cleaned up as well?
- The process instance still there on partition 3 --> Why was the process definition deleted?

## Why was the process definition not found?

### What data to look at?

- Look at Operate process instance
- Download data folder, inspect timer state, process state, process instance state
- On the log stream, can we see a deletion on partition 3?

### Where to look for the data?

1. Operate state for the process instance
2. Zeebe state for the process instance, timers, processes on partition 3
3. ES exported log stream if it's already compacted and not available anymore in the partition data download

**Comment by tmetzke** [comment] 2024-08-08 11:51
# Insights (work in progress)

## Log data investigation

* Event `ELEMENT_COMPLETED` for `bpmnElementType=PROCESS` for the process instance `6755399442538720` at position `2967148` on partition 3
* Event `DELETED` for value type `PROCESS` with `processDefinitionKey = 2251799815154549` at position `2969067` on partition 1
* Event `DELETED` for value type `PROCESS` with `processDefinitionKey = 2251799815154549` at position `2967713` on partition 3

### Observations 

* It seems like the process instance in question was already completed when the process definition was deleted on partition 3. The process deletion would be OK then.
* Somehow, there still was a timer trigger for the process instance (I believe it's a start event timer).
* The latter seems to be the bigger issue here - why was there still a timer for the process instance and process definition?
* Since the process instance is in the banned instances in the partitions runtime state, does that mean that is still was in the runtime data but completed when the timer triggered so the instance could be banned? Or do we simply create an entry for a banned instance based on the key provided by the trigger although that instance might not even be in the runtime data anymore?

**Comment by korthout** [comment] 2024-08-09 07:29
> why was there still a timer for the process instance and process definition?

Could it be that the process instance was completing, a delete process resource was requested and before the complete process instance was processed the timer die date checker appended a timer trigger command?

If you have access to the log, you can verify this by checking that the Timer `TRIGGER` command exists on the log at a position before the process instance `ELEMENT_COMPLETED` event. I.e. the timer trigger was requested before the process instance was completed.

This case should be allowed. So, the timer trigger command processor should consider the case that the process instance (and also the process definition) is gone before the timer trigger command is processed. The context has changed in between requesting the action (writing the command) and processing it.

**Comment by tmetzke** [comment] 2024-08-12 06:18
Thanks a lot, @korthout, for our discussions and your input. I have adjusted the **Insights** comment above to match our results and outcome. Let me know if you have any further additions.

Next possible step: Fix the timer trigger command processor to properly reject the command when the process definition is gone already for start event timer.

**Comment by korthout** [comment] 2024-08-12 07:14
```
{
  "cf": "TIMERS",
  "key": "-1:6755399442538722",
```

Something funky is going on. This timer exists on partition 3, but timer start events (those that create new process instances) are only expected on partition 1 (until we fix #15426). So, how did this timer instance come to exist on partition 3?

**Comment by tmetzke** [comment] 2024-08-12 07:19
Interesting. The process instance was also created on partition 3, looking at `"processInstanceKey": 6755399442538720`, right?

**Comment by korthout** [comment] 2024-08-12 07:20
Yes 👍

**Comment by tmetzke** [comment] 2024-08-16 10:37
@megglos, I couldn't get to work on this anymore before my absence. Unassigning myself and handing it over to you so it's on your radar.

**Comment by tmetzke** [comment] 2024-09-03 11:08
Taking this up again and planning to adjust the timer trigger processor so its rejects instead of failing on a missing process definition.

**Comment by tmetzke** [comment] 2024-09-11 07:09
Provided a potential fix for the process instance banning with https://github.com/camunda/camunda/pull/22169.
The root cause is still unclear though, we don't know how this scenario can be created.

**Closed** 2024-09-12 10:02 UTC
Labels: kind/bug, severity/high, component/engine, component/zeebe, likelihood/unknown
