### ISSUE TITLE
Prioritize export of records to avoid building up a backlog

### ISSUE THREAD

**Issue by pihme** [camunda/camunda#6723] opened 2021-04-01 09:30 UTC
**Is your feature request related to a problem? Please describe.**
I am not sure whether this should be a feature request or a bug report. 

What is needed is a solution for the following problem: 

It can happen that the Zeebe cluster is under such high load that it will take on more work than it can export at the same time. 

This leads to a big backlog of non-exported entries. This big backlog may lead to other problems (many log segments). Eventually, Zeebe will run out of disk space, and throttling will kick in. Then the whole system will effectively be throttled to the speed of the slowest exporter, but it will happen at a time when the system already has a huge backlog.

This was observed in one of our weekly benchmarks. The benchmark had run unresponsive with a huge backlog. We stopped the ingress of new work and waited till all records had been exported to see whether the cluster would recover. The cluster did indeed recover.

However, as soon as we started sending traffic again, the backlog built up again immediately.

The backlog also means that the information available in Operate is delayed. In one back-of-the napkin calculation we arrived at a time delay between Zeebe and Operate of 40 minutes for one of the backlogs we observed. (note also that the backlog was not consistent for all partitions, so the delay in Operate will be different per partition, which is probably difficult to explain to customers)

According to Chris export is done in a single thread in a synchronous way. Zeebe leader had no free CPU capacity, but Elasticsearch and followers did have it.

So this problem is likely to be more pronounced if we have more threads to handle incoming work, whilst only one thread for exporting.

We also did an experiment in which we filtered out the exporting of variable and job records. These are the records with the highest payload. With the reduced payload the backlog does not build up.

So we have an unfortunate behavior which most likely will worsen with more payload and more incoming traffic.

**Describe the solution you'd like**
* Export as fast as possible
  * Export multiple batches in parallel
  * Scale resources for export in tandem with resources for processing records
  * Check if followers could help with exporting
* Improve metrics (see #6721)
* Monitor whether exporter backend is available or not.  (maybe limited to Elasticsearch as this is the only exporter we run in the cloud)
  * When it is available
    * Reduce backlog with priority
    * Once the backlog is empty, throttle average intake to average speed of export
  * When it is not available, build up backlog
* Add metrics/dashboard to point out which part is the bottleneck - is it Zeebe? Is it an exporter? If so, which exporter? 

**Additional context**
This is more a description of a problem, not really a solution. It is not clear how to deal with spikes, how to reliably detect outage of an exporter vs degradation of service of an exporter.

**Comment by megglos** [comment] 2023-04-26 11:44
ZDP-Triage:
- it's a useful feature to backpressure processing if exporting doesn't keep up for all users that make use of webapps/Operate
- it will eventually stall the system => the user can detect that by metrics on the exporter backlog
- there are two relevant objectives
  - align processing throughput with what the exporter can consume
  - cover shorter unavailabilities of e.g. elasticsearch => they shouldn't impact the processing speed
- would help to prevent incidents where processing vs exporter speed causes log buildup

**Comment by megglos** [comment] 2023-04-28 09:38
ZDP-Planning:
- in general this indicates a reassessment of the exporter architecture is due
- will also become more likely with script tasks

**Comment by megglos** [comment] 2023-05-26 09:20
ZDP-Planning:
- given https://github.com/camunda/zeebe/issues/12667 is done, we do not suffer from the startup delay anymore
- backpressure is happening due to disk watermarks

moving to backlog for now to be reassed

**Comment by megglos** [comment] 2023-07-14 09:31
ZDP-Planning:
- we mitigated this by #12957 when it's caused by loops
- we have infrastructure-side measures in place for SaaS (disable disk resize for trial)
- will also be mitigated by a general rate limiting with #12560 
- keeping backlog for now to first focus on #12560

**Comment by megglos** [comment] 2023-08-25 07:14
moving to blocked as we first want to focus on https://github.com/camunda/zeebe/issues/12560

**Comment by npepinpe** [comment] 2024-09-03 18:40
imo achieved via: https://github.com/camunda/camunda/issues/17547

**Closed by npepinpe** 2024-09-03 18:40 UTC
Labels: kind/feature, incident, component/exporter, component/zeebe
