### ISSUE TITLE
IllegalStateException: Expected to find event with the snapshot position 4659997 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-1'.

### ISSUE THREAD

**Issue by wuchuanron** [camunda/camunda#11506] opened 2023-01-31 07:59 UTC
You can see that the snapshot folder named 4659997 has been created, but the prompt cannot be found in the log stream. How to fix this problem.

![image](https://user-images.githubusercontent.com/52146014/215700034-7c351de5-3b8c-44de-ac2c-eb0592d4ba29.png)
![image](https://user-images.githubusercontent.com/52146014/215700095-67df1a16-4267-45b7-b5b4-a0068aabcc9e.png)
![image](https://user-images.githubusercontent.com/52146014/215700118-a0aa08e4-1278-4ca9-b001-c5cab636e3fe.png)

----------------------------------------------

11:38:31.041 [Broker-0-zb-actors-0] ERROR i.c.zeebe.logstreams - [onFailure,325] - Actor Broker-0-StreamProcessor-1 failed in phase STARTED.
java.lang.IllegalStateException: Expected to find event with the snapshot position 4659997 in log stream, but nothing was found. Failed to recover 'Broker-0-StreamProcessor-1'.
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.recoverFromSnapshot(StreamProcessor.java:287)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:124)
at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79)
at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)
at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)
11:38:31.044 [Broker-0-zb-actors-0] ERROR i.c.zeebe.logstreams - [onFailure,325] - Actor Broker-0-StreamProcessor-1 failed in phase FAILED.
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.close()" because "this.replayStateMachine" is null
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.tearDown(StreamProcessor.java:221)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorFailed(StreamProcessor.java:211)
at io.camunda.zeebe.util.sched.ActorTask.fail(ActorTask.java:537)
at io.camunda.zeebe.util.sched.ActorControl.fail(ActorControl.java:419)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onFailure(StreamProcessor.java:326)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorStarted(StreamProcessor.java:169)
at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:79)
at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:44)
at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)
11:38:31.044 [Broker-0-zb-actors-0] ERROR i.c.zeebe.util.actor - [executeCurrentTask,100] - Unexpected error occurred in task Broker-0-StreamProcessor-1 ACTIVE phase: FAILED
java.lang.NullPointerException: Cannot invoke "io.camunda.zeebe.engine.processing.streamprocessor.ReplayStateMachine.close()" because "this.replayStateMachine" is null
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.tearDown(StreamProcessor.java:221)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onActorFailed(StreamProcessor.java:211)
at io.camunda.zeebe.util.sched.ActorTask.fail(ActorTask.java:537)
at io.camunda.zeebe.util.sched.ActorControl.fail(ActorControl.java:419)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.onFailure(StreamProcessor.java:326)
at io.camunda.zeebe.engine.processing.streamprocessor.StreamProcessor.handleFailure(StreamProcessor.java:202)
at io.camunda.zeebe.util.sched.ActorTask.onFailure(ActorTask.java:304)
at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:53)
at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122)
at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:97)
at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:80)
at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:189)

**Comment by Zelldon** [comment] 2023-02-02 07:25
Potential duplicate of https://github.com/camunda/zeebe/issues/9820 

Which version are you running?

Please try to take this leader down, to see whether a different leader can come up.

**Comment by nyarly** [comment] 2023-07-20 23:22
We're also seeing this on version 8.1.9.

Tried tearing down the whole Zeebe node and letting it replicate back into the cluster - it continues to have this issue.

**Comment by npepinpe** [comment] 2024-09-03 19:42
As the issue is quite stale, I'm closing it. Feel free to reopen.

**Closed by npepinpe** 2024-09-03 19:42 UTC
Labels: kind/toil, blocker/info, component/snapshot, component/zeebe
